// Arabic strings for the inventory module (catalog, stock, warehouses, transfers), keyed by the English text.
export const ar: Record<string, string> = {
  // navigation / titles
  'Products': 'المنتجات', 'Product': 'المنتج', 'Services': 'الخدمات', 'Product categories': 'فئات المنتجات', 'Service categories': 'فئات الخدمات', 'Brands': 'العلامات التجارية',
  'Warehouses': 'المستودعات', 'Stock transfers': 'تحويلات المخزون', 'Stock transfer': 'تحويل مخزون', 'Stock': 'المخزون',
  'Catalog, prices and stock for the active store': 'الأصناف والأسعار والمخزون للفرع الحالي', 'Labour, visits and other non-stock items': 'الأجور والزيارات والبنود غير المخزنية',
  'Group products for search, reports and pricing': 'تجميع المنتجات للبحث والتقارير والتسعير', 'Group services for search and reports': 'تجميع الخدمات للبحث والتقارير',
  'Manufacturers and product lines': 'الشركات المصنعة وخطوط المنتجات', 'Stock locations besides the main store': 'مواقع المخزون بخلاف المستودع الرئيسي',
  'Move stock between the main store and warehouses': 'نقل المخزون بين المستودع الرئيسي والمستودعات',
  // create actions
  'New product': 'منتج جديد', 'New service': 'خدمة جديدة', 'New stock transfer': 'تحويل مخزون جديد', 'New transfer': 'تحويل جديد', 'New product category': 'فئة منتجات جديدة',
  'New brand': 'علامة تجارية جديدة', 'New warehouse': 'مستودع جديد', 'New category': 'فئة جديدة', 'New service category': 'فئة خدمات جديدة', 'New Arabic name': 'اسم عربي جديد',
  'New linked product': 'منتج مرتبط جديد', 'Brand details': 'بيانات العلامة التجارية', 'Create brand': 'إنشاء علامة تجارية', 'Create category': 'إنشاء فئة',
  // list views / filters
  'All products': 'كل المنتجات', 'Out of stock': 'نفد من المخزون', 'Out of stock.': 'نفد من المخزون.', 'Kits & sets': 'الأطقم والمجموعات', 'Active': 'نشط', 'Deleted': 'محذوف',
  'Location': 'الموقع', 'Category': 'الفئة', 'Categories': 'الفئات', 'Brand': 'العلامة التجارية', 'Retail price': 'سعر التجزئة', 'Part #': 'رقم القطعة', 'Country': 'الدولة', 'Created': 'تاريخ الإنشاء',
  'Unit': 'الوحدة', 'Delivery': 'التقديم', 'Booking': 'الحجز', 'Duration': 'المدة', 'Required': 'مطلوب', 'Not required': 'غير مطلوب', 'Type': 'النوع', 'Parent': 'الفئة الأم', 'Quantity': 'الكمية', 'Amount': 'المبلغ',
  'Search name, part #, brand, barcode…': 'ابحث بالاسم أو رقم القطعة أو العلامة أو الباركود…', 'Search categories…': 'ابحث في الفئات…', 'Search brands…': 'ابحث في العلامات التجارية…',
  'Search warehouses…': 'ابحث في المستودعات…', 'Search transfer #…': 'ابحث برقم التحويل…', 'Name · item code · category': 'الاسم · رمز الصنف · الفئة', 'Search products…': 'ابحث في المنتجات…',
  'Search products to link…': 'ابحث عن منتجات لربطها…', 'Search English or Arabic…': 'ابحث بالإنجليزية أو العربية…', 'Add category…': 'أضف فئة…',
  'e.g. <=5': 'مثال: ‎<=5', 'e.g. >=10': 'مثال: ‎>=10', 'e.g. >=100': 'مثال: ‎>=100', 'e.g. >=1000': 'مثال: ‎>=1000', 'e.g. >=60': 'مثال: ‎>=60',
  // totals
  'Units in stock': 'الوحدات في المخزون', 'Stock value (cost)': 'قيمة المخزون (التكلفة)', 'Stock value (retail)': 'قيمة المخزون (التجزئة)', 'Stock value (wholesale)': 'قيمة المخزون (الجملة)',
  'Sales': 'المبيعات', 'Sales profit': 'ربح المبيعات', 'Sales returns': 'مرتجعات المبيعات', 'Purchases': 'المشتريات', 'Purchase returns': 'مرتجعات المشتريات', 'Quotations': 'عروض الأسعار',
  'Quotation sales': 'مبيعات عروض الأسعار', 'Delivered qty': 'الكمية المسلمة', 'Transferred value': 'القيمة المحولة', 'Transferred qty': 'الكمية المحولة', 'Totals': 'الإجماليات',
  // columns
  'Name': 'الاسم', 'Barcode': 'الباركود', 'Stock here': 'المخزون هنا', 'Cost': 'التكلفة', 'Wholesale': 'الجملة', 'Retail': 'التجزئة', 'Sold': 'المباع', 'Profit': 'الربح', 'Rack': 'الرف',
  'Created at': 'تاريخ الإنشاء', 'Created by': 'أنشئ بواسطة', 'Updated at': 'تاريخ التحديث', 'Updated by': 'حُدّث بواسطة', 'Kit': 'طقم', 'Code': 'الرمز', 'City': 'المدينة', 'Phone': 'الهاتف',
  'Transfers out': 'تحويلات صادرة', 'Transfers in': 'تحويلات واردة', 'Transfer #': 'رقم التحويل', 'From': 'من', 'To': 'إلى', 'Qty': 'الكمية', 'Value': 'القيمة', 'units': 'وحدة', 'Date': 'التاريخ',
  'Name (Arabic)': 'الاسم (عربي)', 'Part Number': 'رقم القطعة', 'Purchase Price': 'سعر الشراء', 'Wholesale Price': 'سعر الجملة', 'Retail Price': 'سعر التجزئة', 'Created At': 'تاريخ الإنشاء',
  'Total qty': 'إجمالي الكمية', 'Net total': 'الصافي',
  // product view
  'Low stock': 'مخزون منخفض', 'On hand': 'المتوفر', 'Days of cover': 'أيام التغطية', 'Selling price': 'سعر البيع', 'Sold (30d)': 'المباع (30 يوماً)', 'pcs': 'قطعة',
  'Overview': 'نظرة عامة', 'Stock movements': 'حركات المخزون', 'Prices': 'الأسعار', 'Kit components': 'مكونات الطقم', 'Linked products': 'المنتجات المرتبطة', 'Photos': 'الصور', 'Insights': 'التحليلات',
  'Create purchase order': 'إنشاء أمر شراء', 'Create purchase': 'إنشاء فاتورة شراء', 'Transfer': 'تحويل', 'Edit': 'تعديل', 'Restore': 'استعادة', 'Delete': 'حذف', 'Sections': 'الأقسام',
  '{{n}} left — about {{d}} days of stock.': 'متبقٍ {{n}} — حوالي {{d}} يوماً من المخزون.', 'Suggested order: {{q}} {{u}} from {{v}}.': 'الطلب المقترح: {{q}} {{u}} من {{v}}.',
  'Suggested order: {{q}} {{u}}.': 'الطلب المقترح: {{q}} {{u}}.', 'Units sold per month': 'الوحدات المباعة شهرياً', 'Stock by location': 'المخزون حسب الموقع', 'Main Store': 'المستودع الرئيسي',
  'Details': 'التفاصيل', 'Name in Arabic': 'الاسم بالعربية', 'Item code': 'رمز الصنف', 'EAN-12': 'EAN-12', 'Old barcode': 'الباركود القديم', 'Piece': 'قطعة', 'Store code': 'رمز الفرع',
  'Duplicates allowed': 'السماح بالتكرار', 'Yes': 'نعم', 'No': 'لا', 'Barcode label': 'ملصق الباركود', 'No barcode available.': 'لا يوجد باركود.', 'Copies': 'عدد النسخ', 'Print label': 'طباعة الملصق',
  'Unit prices': 'أسعار الوحدة', 'Tier': 'الفئة السعرية', 'Excl. VAT': 'غير شامل الضريبة', 'Incl. VAT': 'شامل الضريبة', 'Margin': 'هامش الربح', 'Auto-update': 'تحديث تلقائي',
  'Purchase': 'الشراء', 'Last purchase': 'آخر شراء', 'Stock adjustments': 'تسويات المخزون', 'No adjustments': 'لا توجد تسويات', 'Add or remove stock from the edit screen.': 'أضف أو اسحب المخزون من شاشة التعديل.',
  'Added': 'مضاف', 'Removed': 'مسحوب', 'Reason': 'السبب', 'Item': 'الصنف', 'Share': 'الحصة', 'Total': 'الإجمالي',
  'No linked products': 'لا توجد منتجات مرتبطة', 'Link alternatives or accessories from the edit screen.': 'اربط البدائل أو الملحقات من شاشة التعديل.',
  'Demand profile': 'ملف الطلب', 'Velocity trend': 'اتجاه سرعة البيع', 'Slope / month': 'الميل / شهر', 'Momentum / 3 months': 'الزخم / 3 أشهر', 'Avg. monthly qty': 'متوسط الكمية الشهرية',
  'Last 3 months qty': 'كمية آخر 3 أشهر', 'ABC / XYZ tier': 'تصنيف ABC / XYZ', 'Class': 'الفئة', 'Stocking strategy': 'استراتيجية التخزين', 'Revenue': 'الإيراد', 'History': 'السجل',
  'No history yet': 'لا يوجد سجل بعد', 'Month': 'الشهر', 'Pricing': 'التسعير', 'Retail incl. VAT': 'التجزئة شامل الضريبة', 'Recent movements': 'آخر الحركات', 'No movements yet.': 'لا توجد حركات بعد.',
  'Record': 'السجل', 'Photos uploaded': 'تم رفع الصور', 'Photo deleted': 'تم حذف الصورة', 'Product photo': 'صورة المنتج', 'Delete photo': 'حذف الصورة', 'Delete this photo?': 'حذف هذه الصورة؟',
  'Add photos': 'إضافة صور', 'Uploads on save': 'تُرفع عند الحفظ', 'No photos yet.': 'لا توجد صور بعد.',
  // movements
  'Reference': 'المرجع', 'Customer / vendor': 'العميل / المورد', 'Stock after': 'المخزون بعد', 'Unit price': 'سعر الوحدة', 'Discount': 'الخصم', 'Price': 'السعر', 'VAT': 'الضريبة', 'Net': 'الصافي',
  'Profit / loss': 'الربح / الخسارة', 'Sales return': 'مرتجع مبيعات', 'Purchase return': 'مرتجع مشتريات', 'Quotation': 'عرض سعر', 'Quotation sale': 'بيع من عرض سعر',
  'Quotation sales return': 'مرتجع مبيعات عرض سعر', 'Delivery note': 'إشعار تسليم', 'Stock added': 'إضافة مخزون', 'Stock removed': 'سحب مخزون',
  // list actions
  'Migrate racks': 'ترحيل الرفوف', 'Copy legacy racks to Main Store?': 'نسخ الرفوف القديمة إلى المستودع الرئيسي؟', 'Migrate': 'ترحيل',
  'Each product’s old rack value is copied into its Main Store rack location.': 'تُنسخ قيمة الرف القديمة لكل منتج إلى موقع رف المستودع الرئيسي.', '{{n}} products updated': 'تم تحديث {{n}} منتج',
  'Delete {{noun}}?': 'حذف {{noun}}؟', 'product': 'المنتج', 'service': 'الخدمة', 'category': 'الفئة', 'service category': 'فئة الخدمة', 'brand': 'العلامة التجارية', 'warehouse': 'المستودع',
  'It can be restored later from the Deleted view.': 'يمكن استعادته لاحقاً من عرض المحذوفات.', 'This can’t be undone.': 'لا يمكن التراجع عن هذا.', 'Undo': 'تراجع', 'Restored': 'تمت الاستعادة', 'Remove': 'إزالة',
  // product editor
  'Identity': 'الهوية', 'Classification': 'التصنيف', 'Arabic names list': 'قائمة الأسماء العربية', 'Pick a saved translation or add a new one.': 'اختر ترجمة محفوظة أو أضف واحدة جديدة.',
  'Add new Arabic name': 'إضافة اسم عربي جديد', 'Name in English': 'الاسم بالإنجليزية', 'Part # prefix': 'بادئة رقم القطعة', 'Leave blank to auto-generate': 'اتركه فارغاً للتوليد التلقائي',
  'Item code / SKU': 'رمز الصنف / SKU', 'Barcode (EAN-12)': 'الباركود (EAN-12)', 'Assigned automatically': 'يُعيّن تلقائياً', 'Country of origin': 'بلد المنشأ',
  'Piece (PCE)': 'قطعة (PCE)', 'Drum (DRM)': 'برميل (DRM)', 'Set (SET)': 'طقم (SET)', 'Kilogram (KGM)': 'كيلوغرام (KGM)', 'Metre (MTR)': 'متر (MTR)', 'Centimetre (CMT)': 'سنتيمتر (CMT)',
  'Millimetre (MMT)': 'مليمتر (MMT)', 'Gram (GRM)': 'غرام (GRM)', 'Litre (LTR)': 'لتر (LTR)', 'Milligram (MG)': 'مليغرام (MG)',
  'Priced from kit components': 'مُسعّر من مكونات الطقم', 'Auto-update wholesale from last purchase': 'تحديث سعر الجملة تلقائياً من آخر شراء', 'Auto-update retail from last purchase': 'تحديث سعر التجزئة تلقائياً من آخر شراء',
  'Update wholesale now': 'تحديث الجملة الآن', 'Update retail now': 'تحديث التجزئة الآن', 'Set Retail Margin % first': 'حدد نسبة هامش التجزئة أولاً', 'Set Wholesale Margin % first': 'حدد نسبة هامش الجملة أولاً',
  'No purchase found for this product': 'لم يتم العثور على شراء لهذا المنتج', 'Price updated from {{code}}': 'تم تحديث السعر من {{code}}', 'last purchase': 'آخر شراء',
  'Location & options': 'الموقع والخيارات', 'Allow duplicates in sales, purchases etc.': 'السماح بالتكرار في المبيعات والمشتريات وغيرها', 'Note': 'ملاحظة', 'Current stock levels': 'مستويات المخزون الحالية',
  'Opening stock, damages, counts — saved with the product.': 'المخزون الافتتاحي والتالف والجرد — يُحفظ مع المنتج.', 'Adjustment quantity': 'كمية التسوية', 'Enter quantity': 'أدخل الكمية',
  'Add stock': 'إضافة مخزون', 'Remove stock': 'سحب مخزون', 'Adjustment date': 'تاريخ التسوية', 'Adjustment type': 'نوع التسوية', 'Add': 'إضافة', 'Enter a quantity greater than 0': 'أدخل كمية أكبر من 0',
  'Kit / set': 'طقم / مجموعة', 'Sell several products as one; their prices make up this product’s price.': 'بيع عدة منتجات كمنتج واحد؛ تشكّل أسعارها سعر هذا المنتج.', 'Set name': 'اسم الطقم',
  'Add component': 'إضافة مكون', 'Line': 'السطر', 'incl. VAT': 'شامل الضريبة', 'Alternatives and accessories — links are kept on both products.': 'البدائل والملحقات — يُحفظ الربط في كلا المنتجين.',
  'Photos upload right after the product is created.': 'تُرفع الصور مباشرة بعد إنشاء المنتج.', 'Will be linked to the product you came from.': 'سيُربط بالمنتج الذي أتيت منه.',
  'Some photos could not be uploaded': 'تعذر رفع بعض الصور', '{{name}} created': 'تم إنشاء {{name}}', 'Please fix the highlighted fields.': 'يرجى تصحيح الحقول المحددة.', 'Couldn’t save.': 'تعذر الحفظ.',
  'Draft': 'مسودة', 'Unsaved': 'غير محفوظ', 'Discard': 'تجاهل', 'Close': 'إغلاق', 'Create': 'إنشاء', 'Save': 'حفظ', 'Save changes': 'حفظ التغييرات', 'Saved': 'تم الحفظ', 'Cancel': 'إلغاء', 'New': 'جديد', 'Print': 'طباعة',
  // validation
  'Name is required': 'الاسم مطلوب', 'Name length should be min. 3 chars': 'يجب ألا يقل الاسم عن 3 أحرف', 'Name length should be max. 500 chars': 'يجب ألا يزيد الاسم عن 500 حرف',
  'Price should not be < 0': 'يجب ألا يقل السعر عن 0', 'Date is required': 'التاريخ مطلوب', 'Type is required': 'النوع مطلوب', 'Quantity should be > 0': 'يجب أن تكون الكمية أكبر من 0',
  'Quantity is required': 'الكمية مطلوبة', 'Unit is required': 'الوحدة مطلوبة', 'Invalid phone no.': 'رقم هاتف غير صالح', 'Invalid email': 'بريد إلكتروني غير صالح',
  'Building number must be 4 digits': 'يجب أن يتكون رقم المبنى من 4 أرقام', 'Zip code must be 5 digits': 'يجب أن يتكون الرمز البريدي من 5 أرقام',
  'Both From & To warehouse cannot be Main Store': 'لا يمكن أن يكون المصدر والوجهة كلاهما المستودع الرئيسي', 'Choose different warehouse': 'اختر مستودعاً مختلفاً',
  // services
  'Service category': 'فئة الخدمة', 'Service category name': 'اسم فئة الخدمة', 'Each / Per visit (C62)': 'لكل وحدة / زيارة (C62)', 'Hour (HUR)': 'ساعة (HUR)', 'Day (DAY)': 'يوم (DAY)',
  'Week (WEE)': 'أسبوع (WEE)', 'Month (MON)': 'شهر (MON)', 'Year (ANN)': 'سنة (ANN)', 'Duration unit': 'وحدة المدة', 'Minutes': 'دقائق', 'Hours': 'ساعات', 'Days': 'أيام', 'Weeks': 'أسابيع',
  'Delivery mode': 'طريقة التقديم', '— Not specified —': '— غير محدد —', 'In store': 'في المحل', 'Remote / online': 'عن بُعد / عبر الإنترنت', 'At customer location': 'في موقع العميل',
  'Booking required': 'يتطلب حجزاً', 'Description / notes': 'الوصف / الملاحظات', 'Each / Per visit': 'لكل وحدة / زيارة', 'Hour': 'ساعة', 'Day': 'يوم', 'Week': 'أسبوع', 'Year': 'سنة',
  // warehouses
  'Email': 'البريد الإلكتروني', 'Short code': 'الرمز المختصر', 'Building no.': 'رقم المبنى', 'Street': 'الشارع', 'Street (Arabic)': 'الشارع (عربي)', 'District': 'الحي', 'District (Arabic)': 'الحي (عربي)',
  'City (Arabic)': 'المدينة (عربي)', 'Zip code': 'الرمز البريدي', 'Additional no.': 'الرقم الإضافي', 'Unit no.': 'رقم الوحدة', '4 digits': '4 أرقام', '5 digits': '5 أرقام',
  '05XXXXXXXX / +9665XXXXXXXX': '05XXXXXXXX / +9665XXXXXXXX', 'Parent category': 'الفئة الأم',
  // transfers
  'Items': 'الأصناف', 'Warning': 'تنبيه', 'available stock in {{loc}} is {{n}}': 'المخزون المتاح في {{loc}} هو {{n}}', 'Previous transfer': 'التحويل السابق', 'Next transfer': 'التحويل التالي',
  'This is the first transfer.': 'هذا أول تحويل.', 'This is the latest transfer.': 'هذا آخر تحويل.', 'Value incl. VAT': 'القيمة شاملة الضريبة', 'Subtotal': 'المجموع الفرعي', 'Rounding': 'التقريب',
  'Disc.': 'الخصم', 'Remarks': 'ملاحظات', 'in stock': 'في المخزون', '—': '—',
};
