/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./src/**/*.{js,jsx,ts,tsx}'],
  corePlugins: {
    preflight: false,
  },
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'on-surface-variant': '#434655',
        'outline': '#737686',
        'on-error': '#ffffff',
        'surface-variant': '#d8e3fb',
        'inverse-primary': '#b4c5ff',
        'surface-container': '#e7eeff',
        'error': '#ba1a1a',
        'surface-dim': '#cfdaf2',
        'surface-container-low': '#f0f3ff',
        'on-primary-container': '#eeefff',
        'primary-container': '#2563eb',
        'outline-variant': '#c3c6d7',
        'on-tertiary-fixed': '#191c1e',
        'tertiary-fixed-dim': '#c4c7c9',
        'surface-container-high': '#dee8ff',
        'on-primary-fixed': '#00174b',
        'tertiary-container': '#6b6e70',
        'inverse-on-surface': '#ecf1ff',
        'tertiary-fixed': '#e0e3e5',
        'primary-fixed-dim': '#b4c5ff',
        'surface-container-lowest': '#ffffff',
        'on-secondary-fixed-variant': '#38485d',
        'secondary-fixed': '#d3e4fe',
        'on-secondary': '#ffffff',
        'background': '#f9f9ff',
        'tertiary': '#525657',
        'primary': '#004ac6',
        'on-tertiary-fixed-variant': '#444749',
        'secondary': '#505f76',
        'surface': '#f9f9ff',
        'on-error-container': '#93000a',
        'on-tertiary': '#ffffff',
        'secondary-container': '#d0e1fb',
        'on-tertiary-container': '#eff1f3',
        'inverse-surface': '#263143',
        'error-container': '#ffdad6',
        'on-surface': '#111c2d',
        'surface-bright': '#f9f9ff',
        'surface-tint': '#0053db',
        'on-secondary-container': '#54647a',
        'primary-fixed': '#dbe1ff',
        'on-primary-fixed-variant': '#003ea8',
        'on-primary': '#ffffff',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      spacing: {
        xl: '32px',
        md: '16px',
        xs: '8px',
        gutter: '16px',
        base: '4px',
        lg: '24px',
        'container-padding': '24px',
        'container-margin': '40px',
        sm: '12px',
      },
      fontFamily: {
        'body-lg': ['Inter'],
        'label-sm': ['Inter'],
        'data-mono': ['JetBrains Mono'],
        'label-md': ['Inter'],
        'headline-sm': ['Hanken Grotesk'],
        'headline-md': ['Hanken Grotesk'],
        'headline-lg': ['Hanken Grotesk'],
        'body-md': ['Inter'],
      },
      fontSize: {
        'body-lg': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'label-sm': ['11px', { lineHeight: '14px', fontWeight: '500' }],
        'data-mono': ['13px', { lineHeight: '18px', fontWeight: '500' }],
        'label-md': ['12px', { lineHeight: '16px', fontWeight: '600' }],
        'headline-sm': ['18px', { lineHeight: '26px', fontWeight: '600' }],
        'headline-md': ['18px', { lineHeight: '24px', fontWeight: '600' }],
        'headline-lg': ['22px', { lineHeight: '28px', letterSpacing: '-0.01em', fontWeight: '700' }],
        'body-md': ['13px', { lineHeight: '18px', fontWeight: '400' }],
      },
    },
  },
  plugins: [
    require('@tailwindcss/forms')({ strategy: 'class' }),
    require('@tailwindcss/container-queries'),
  ],
};
