/** Arabic strings for the Buying module, keyed by the English text. */
export const ar: Record<string, string> = {
  // navigation & titles
  'Buying': 'المشتريات', 'Purchase bills': 'فواتير المشتريات', 'Purchase bill': 'فاتورة مشتريات', 'Purchase bill #': 'رقم فاتورة المشتريات', 'Purchase returns': 'مرتجعات المشتريات',
  'Purchase return': 'مرتجع مشتريات', 'Purchase orders': 'أوامر الشراء', 'Purchase order': 'أمر شراء', 'Purchase requests': 'طلبات الشراء', 'Purchase request': 'طلب شراء',
  'Purchase payments': 'مدفوعات المشتريات', 'Return refunds': 'استردادات المرتجعات', 'Cash discounts': 'الخصومات النقدية', 'Vendors': 'الموردون', 'Vendor': 'المورد',
  'Bill images & PDFs': 'صور وملفات الفواتير', 'Vendor categories': 'فئات الموردين',
  'Vendor bills received into stock': 'فواتير الموردين المستلمة في المخزون', 'Goods sent back to vendors': 'بضائع مرتجعة إلى الموردين',
  'Orders sent to vendors before goods arrive': 'أوامر مرسلة للموردين قبل وصول البضاعة', 'Internal requests to buy stock, sent between users': 'طلبات داخلية لشراء المخزون بين المستخدمين',
  'Payments made to vendors against purchase bills': 'مدفوعات للموردين مقابل فواتير المشتريات',
  'Refunds received from vendors for purchase returns — record new ones from the return': 'المبالغ المستردة من الموردين عن المرتجعات — سجّل الجديد من شاشة المرتجع',
  'Settlement discounts granted by vendors on purchase bills': 'خصومات السداد الممنوحة من الموردين على فواتير المشتريات',
  'Suppliers you buy from, with balances for the active store': 'الموردون الذين تشتري منهم مع أرصدتهم في الفرع الحالي',
  'Scanned vendor bills — extract them with AI and turn them into purchase bills': 'فواتير الموردين الممسوحة — استخرجها بالذكاء الاصطناعي وحوّلها إلى فواتير مشتريات',
  // create actions
  'New purchase': 'مشتريات جديدة', 'New purchase bill': 'فاتورة مشتريات جديدة', 'New purchase return': 'مرتجع مشتريات جديد', 'New return': 'مرتجع جديد',
  'New purchase order': 'أمر شراء جديد', 'New order': 'أمر جديد', 'New purchase request': 'طلب شراء جديد', 'New request': 'طلب جديد', 'New vendor': 'مورد جديد',
  'New category': 'فئة جديدة', 'New cash discount': 'خصم نقدي جديد', 'Edit vendor': 'تعديل المورد', 'Edit category': 'تعديل الفئة', 'Edit cash discount': 'تعديل الخصم النقدي',
  'Edit payment': 'تعديل الدفعة', 'Delete payment': 'حذف الدفعة', 'Record payment': 'تسجيل دفعة', 'Record refund': 'تسجيل استرداد',
  // list views & filters
  'All bills': 'كل الفواتير', 'To pay': 'مستحقة الدفع', 'With returns': 'بها مرتجعات', 'All returns': 'كل المرتجعات', 'Refund due': 'استرداد مستحق', 'Refunded': 'مسترد',
  'All orders': 'كل الأوامر', 'All requests': 'كل الطلبات', 'All vendors': 'كل الموردين', 'With balance': 'لها رصيد', 'Unpaid bills': 'فواتير غير مدفوعة', 'Deleted': 'محذوف', 'Active': 'نشط',
  'Received': 'المستلمة', 'Sent': 'مرسل', 'Any status': 'أي حالة', 'Vendor invoice #': 'رقم فاتورة المورد', 'Vendor return invoice #': 'رقم فاتورة مرتجع المورد',
  'Created': 'تاريخ الإنشاء', 'Category': 'الفئة', 'Categories': 'الفئات', 'e.g. >=1000': 'مثال: >=1000', 'e.g. >=100': 'مثال: >=100', 'e.g. >0': 'مثال: >0',
  'Search bill # or vendor invoice #…': 'ابحث برقم الفاتورة أو رقم فاتورة المورد…', 'Search return # or vendor return invoice #…': 'ابحث برقم المرتجع أو رقم فاتورة المورد…',
  'Search PO # or vendor…': 'ابحث برقم أمر الشراء أو المورد…', 'Search request #…': 'ابحث برقم الطلب…', 'Search bill #…': 'ابحث برقم الفاتورة…', 'Search return #…': 'ابحث برقم المرتجع…',
  'Search name, phone, VAT no., code…': 'ابحث بالاسم أو الجوال أو الرقم الضريبي أو الرمز…', 'Search sender or phone…': 'ابحث بالمرسل أو الجوال…', 'Search PO #': 'ابحث برقم أمر الشراء',
  'Search users…': 'ابحث عن مستخدم…', 'Filter…': 'تصفية…', 'Filter categories': 'تصفية الفئات', 'Select…': 'اختر…',
  // columns & totals
  'Bill #': 'رقم الفاتورة', 'Return #': 'رقم المرتجع', 'PO #': 'رقم أمر الشراء', 'Request #': 'رقم الطلب', 'Number': 'الرقم', 'Inv.': 'فاتورة', 'Methods': 'طرق الدفع',
  'Cash disc.': 'خصم نقدي', 'Cash discount': 'خصم نقدي', 'Returns': 'المرتجعات', 'Purchases': 'المشتريات', 'Paid': 'مدفوع', 'Credit (unpaid)': 'آجل (غير مدفوع)', 'Cash': 'نقدي', 'Bank': 'بنك',
  'VAT paid': 'الضريبة المدفوعة', 'Discount': 'الخصم', 'Set off against bills': 'مقاصة مع الفواتير', 'Order value': 'قيمة الأوامر', 'Orders': 'الأوامر', 'Expected': 'المتوقع',
  'Expected date': 'التاريخ المتوقع', 'Qty': 'الكمية', 'Items': 'الأصناف', 'Item': 'الصنف', 'Payable': 'مستحق للموردين', 'Bills': 'الفواتير', 'Total paid': 'إجمالي المدفوع',
  'Total refunded': 'إجمالي المسترد', 'Total cash discount': 'إجمالي الخصم النقدي', 'Amount before VAT': 'المبلغ قبل الضريبة', 'Credit limit': 'حد الائتمان', 'P.O.': 'أمر الشراء',
  'From': 'من', 'To': 'إلى', 'Refunds': 'المبالغ المستردة', 'Purchase': 'مشتريات', 'Vendor account': 'حساب المورد', 'Sales': 'مبيعات',
  // statuses
  'Draft': 'مسودة', 'Confirmed': 'مؤكد', 'Partially received': 'مستلم جزئياً', 'Cancelled': 'ملغى', 'Pending': 'قيد الانتظار', 'Accepted': 'مقبول',
  'Partially accepted': 'مقبول جزئياً', 'Rejected': 'مرفوض', 'Requested': 'تم الطلب', 'Ordered': 'تم الطلب من المورد', 'Linked': 'مرتبط', 'Not linked': 'غير مرتبط',
  // editor
  'Commission': 'العمولة', 'Commission paid by': 'دُفعت العمولة عبر', 'Post to accounts': 'ترحيل إلى الحسابات', 'From P.O.': 'من أمر شراء',
  'Selling prices': 'أسعار البيع', 'updated on the product when you save': 'تُحدَّث على الصنف عند الحفظ', 'Check the highlighted prices.': 'راجع الأسعار المحددة.',
  'Prices of products set to follow the last purchase are recalculated from their margin automatically.': 'أسعار الأصناف المرتبطة بآخر شراء يُعاد حسابها تلقائياً من هامش الربح.',
  'Cost': 'التكلفة', 'Retail price': 'سعر التجزئة', 'Wholesale price': 'سعر الجملة', 'Unit price': 'سعر الوحدة',
  'Purchase price is higher than the retail price.': 'سعر الشراء أعلى من سعر التجزئة.', 'Purchase price is higher than the wholesale price.': 'سعر الشراء أعلى من سعر الجملة.',
  'Services can’t be purchased.': 'لا يمكن شراء الخدمات.', 'Commission can’t be negative.': 'لا يمكن أن تكون العمولة سالبة.', 'Choose how the commission was paid.': 'اختر طريقة دفع العمولة.',
  'Copy lines from a purchase order': 'نسخ الأصناف من أمر شراء', 'No purchase orders found': 'لا توجد أوامر شراء', 'Lines copied from': 'تم نسخ الأصناف من',
  'the order is marked as received when you save this bill.': 'سيُعلَّم الأمر كمستلم عند حفظ هذه الفاتورة.', '{{code}} marked as received': 'تم تعليم {{code}} كمستلم',
  'Bill image linked to {{code}}': 'تم ربط صورة الفاتورة بـ {{code}}', 'Ordered by': 'طلبه', 'Bill': 'الفاتورة', 'No cash discounts recorded.': 'لا توجد خصومات نقدية.',
  // returns
  'Returned by': 'أرجعه', 'Selected user': 'المستخدم المحدد', 'Reload all items': 'إعادة تحميل كل الأصناف', 'Choose who returned the goods.': 'اختر من قام بإرجاع البضاعة.',
  '{{n}} of {{m}} returnable items selected — remove the lines you are not returning.': 'تم اختيار {{n}} من {{m}} صنفاً قابلاً للإرجاع — احذف الأصناف التي لن ترجعها.',
  'Which purchase bill are you returning goods from?': 'من أي فاتورة مشتريات ترجع البضاعة؟',
  'Returns are always created from a purchase bill so quantities and prices match what was bought.': 'تُنشأ المرتجعات دائماً من فاتورة مشتريات لتطابق الكميات والأسعار ما تم شراؤه.',
  'Everything on {{code}} has already been returned.': 'تم إرجاع كل أصناف {{code}} مسبقاً.', 'Choose another bill': 'اختر فاتورة أخرى',
  'This bill was paid — record the refund you receive from the vendor in the payment panel.': 'هذه الفاتورة مدفوعة — سجّل المبلغ المسترد من المورد في لوحة الدفع.',
  'No products selected': 'لم يتم اختيار أصناف', 'This item is not on the original purchase.': 'هذا الصنف غير موجود في فاتورة الشراء الأصلية.', 'Only {{n}} can be returned.': 'يمكن إرجاع {{n}} فقط.',
  'Enter a Saudi mobile number (05XXXXXXXX) or leave it empty.': 'أدخل رقم جوال سعودي (05XXXXXXXX) أو اتركه فارغاً.',
  'Refund due from vendor': 'استرداد مستحق من المورد', 'Refund of {{a}} recorded': 'تم تسجيل استرداد بمبلغ {{a}}',
  'Enter an amount greater than zero.': 'أدخل مبلغاً أكبر من صفر.', 'Amount can’t exceed the balance due ({{b}}).': 'لا يمكن أن يتجاوز المبلغ الرصيد المستحق ({{b}}).', 'Date is required': 'التاريخ مطلوب',
  // orders
  'Convert to purchase': 'تحويل إلى فاتورة مشتريات', 'Convert {{code}} to a purchase bill?': 'تحويل {{code}} إلى فاتورة مشتريات؟', 'Continue': 'متابعة',
  'A new purchase bill opens with the order’s lines. The order is marked as received when you save the bill.': 'تُفتح فاتورة مشتريات جديدة بأصناف الأمر، ويُعلَّم الأمر كمستلم عند حفظ الفاتورة.',
  'Change status': 'تغيير الحالة', 'Status changed to {{s}}': 'تم تغيير الحالة إلى {{s}}', 'Previous order': 'الأمر السابق', 'Next order': 'الأمر التالي', 'No more orders.': 'لا توجد أوامر أخرى.',
  'Delete {{code}}?': 'حذف {{code}}؟', '{{code}} deleted': 'تم حذف {{code}}', 'The purchase order is permanently deleted. This can’t be undone.': 'سيُحذف أمر الشراء نهائياً ولا يمكن التراجع.',
  'This order was cancelled.': 'تم إلغاء هذا الأمر.', 'Creating an order for request': 'إنشاء أمر شراء للطلب',
  // requests
  'Assign to': 'إسناد إلى', 'Assigned to': 'مُسند إلى', 'Choose who should handle this request.': 'اختر من سيتولى هذا الطلب.', 'Accept': 'قبول', 'Partially accept': 'قبول جزئي',
  'Reject': 'رفض', 'Reject {{code}}?': 'رفض {{code}}؟', 'Create P.O.': 'إنشاء أمر شراء', '{{code}} accepted': 'تم قبول {{code}}', '{{code}} partially accepted': 'تم قبول {{code}} جزئياً',
  '{{code}} rejected': 'تم رفض {{code}}', 'The request is permanently deleted. This can’t be undone.': 'سيُحذف الطلب نهائياً ولا يمكن التراجع.', 'Saved views': 'طرق العرض',
  // payments
  'Delete this payment?': 'حذف هذه الدفعة؟', '{{a}} on {{code}} is removed and the bill’s balance goes back up.': 'ستُحذف {{a}} من {{code}} ويرتفع رصيد الفاتورة.', 'Payment deleted': 'تم حذف الدفعة',
  'Saving replaces the cash discount on the bill with the total of its cash-discount records.': 'الحفظ يستبدل الخصم النقدي في الفاتورة بمجموع سجلات الخصم النقدي.',
  'Cash discount must be less than the bill total ({{b}}).': 'يجب أن يكون الخصم النقدي أقل من إجمالي الفاتورة ({{b}}).',
  // vendors
  'Name (Arabic)': 'الاسم بالعربية', 'Phone 2': 'الجوال 2', 'Contact person': 'جهة الاتصال', 'C.R. no.': 'رقم السجل التجاري', 'VAT %': 'نسبة الضريبة %', 'Product categories': 'فئات المنتجات',
  'Address': 'العنوان', 'Building no.': 'رقم المبنى', 'Street': 'الشارع', 'District': 'الحي', 'City': 'المدينة', 'Postal code': 'الرمز البريدي', 'Additional no.': 'الرقم الإضافي', 'Unit no.': 'رقم الوحدة',
  'Use remarks in purchases': 'استخدام الملاحظات في المشتريات', 'Opening balance': 'الرصيد الافتتاحي', 'Balance direction': 'اتجاه الرصيد', 'Store owes vendor': 'المتجر مدين للمورد',
  'Vendor owes store': 'المورد مدين للمتجر', 'Opening balance as of': 'تاريخ الرصيد الافتتاحي', '15 digits, starts and ends with 3': '15 رقماً تبدأ وتنتهي بالرقم 3',
  'Type a category and press Enter': 'اكتب فئة واضغط Enter', 'No vendor categories yet.': 'لا توجد فئات موردين بعد.', 'No categories': 'لا توجد فئات', 'Category deleted': 'تم حذف الفئة',
  'Delete category “{{n}}”?': 'حذف الفئة «{{n}}»؟', 'Delete {{n}}?': 'حذف {{n}}؟', '{{n}} deleted': 'تم حذف {{n}}', '{{n}} restored': 'تمت استعادة {{n}}', 'Restore': 'استعادة',
  'The vendor is hidden from lists. You can restore it later.': 'سيُخفى المورد من القوائم ويمكن استعادته لاحقاً.', 'Overview': 'نظرة عامة', 'Contact': 'التواصل',
  'Tax & registration': 'الضريبة والتسجيل', 'National address': 'العنوان الوطني', 'Purchasing': 'المشتريات', 'Classification': 'التصنيف', 'Add. no.': 'رقم إضافي',
  'copied onto purchases': 'تُنسخ إلى المشتريات', 'paid': 'مدفوعة', 'partially': 'جزئياً', 'unpaid': 'غير مدفوعة', 'Balance': 'الرصيد', 'Arabic name': 'الاسم بالعربية',
  'Name is required': 'الاسم مطلوب', 'VAT No. must be 15 digits, starting and ending with 3': 'يجب أن يتكون الرقم الضريبي من 15 رقماً يبدأ وينتهي بـ 3', 'Invalid e-mail': 'بريد إلكتروني غير صالح',
  'C.R. No. must be letters and digits only': 'يجب أن يحتوي السجل التجاري على حروف وأرقام فقط', 'Enter a VAT % between 0 and 100': 'أدخل نسبة ضريبة بين 0 و100',
  'Opening balance can’t be negative': 'لا يمكن أن يكون الرصيد الافتتاحي سالباً',
  // bills
  'Upload bills': 'رفع فواتير', 'Upload purchase bills': 'رفع فواتير مشتريات', 'Upload': 'رفع', 'Drop images or PDFs here, or click to choose': 'أفلت الصور أو ملفات PDF هنا أو انقر للاختيار',
  'Each file is stored as one bill.': 'يُحفظ كل ملف كفاتورة مستقلة.', 'Choose files': 'اختر الملفات', '{{n}} bill(s) uploaded': 'تم رفع {{n}} فاتورة', 'No bills yet': 'لا توجد فواتير بعد',
  'Upload photos or PDFs of vendor bills to keep them with your purchases.': 'ارفع صور أو ملفات PDF لفواتير الموردين لحفظها مع مشترياتك.', 'Open file': 'فتح الملف', 'file(s)': 'ملف',
  'Extract': 'استخراج', 'Extract bill': 'استخراج الفاتورة', 'Link': 'ربط', 'Link to purchase bill': 'ربط بفاتورة مشتريات', 'View purchase': 'عرض المشتريات', 'Delete this bill?': 'حذف هذه الفاتورة؟',
  'The uploaded image or PDF is deleted. This can’t be undone.': 'سيُحذف الملف المرفوع ولا يمكن التراجع.', 'Bill deleted': 'تم حذف الفاتورة', 'AI provider': 'مزود الذكاء الاصطناعي', 'Model': 'النموذج',
  'Leave blank for the provider default.': 'اتركه فارغاً لاستخدام النموذج الافتراضي.', 'Extraction complete': 'اكتمل الاستخراج', 'Invoice date': 'تاريخ الفاتورة', 'Invoice #': 'رقم الفاتورة',
  'Extracted items': 'الأصناف المستخرجة', 'Part #': 'رقم القطعة', 'Create purchase': 'إنشاء فاتورة مشتريات',
  'Missing vendors and products are created automatically when you continue.': 'سيتم إنشاء الموردين والأصناف غير الموجودة تلقائياً عند المتابعة.',
  // misc
  'PDF': 'PDF', 'WhatsApp': 'واتساب', 'Refresh': 'تحديث', 'Remove': 'إزالة', 'Sections': 'الأقسام', 'Payments': 'المدفوعات', 'Return': 'مرتجع', 'Create return': 'إنشاء مرتجع',
  'Total incl. VAT': 'الإجمالي شامل الضريبة', 'Balance due': 'المبلغ المستحق', 'Payment': 'الدفع', 'Payment status': 'حالة الدفع', 'Payment method': 'طريقة الدفع', 'Method': 'الطريقة',
  'Amount': 'المبلغ', 'Note': 'ملاحظة', 'Total': 'الإجمالي', 'VAT': 'الضريبة', 'Date': 'التاريخ', 'Status': 'الحالة', 'Created by': 'أنشأه', 'Created at': 'تاريخ الإنشاء', 'Loading…': 'جارٍ التحميل…',
};
