// Arabic strings for the administration module, keyed by the English source text.
export const ar: Record<string, string> = {
  // Navigation / pages
  'Admin': 'الإدارة', 'Stores': 'الفروع', 'Store': 'الفرع', 'Users': 'المستخدمون', 'User': 'مستخدم', 'Roles': 'الأدوار', 'Role': 'الدور',
  'Roles & permissions': 'الأدوار والصلاحيات', 'Roles & permissions (RBAC)': 'الأدوار والصلاحيات (RBAC)', 'Signatures': 'التوقيعات', 'Signature': 'التوقيع',
  'Menu settings': 'إعدادات القائمة', 'Store settings': 'إعدادات الفرع', 'Settings': 'الإعدادات',
  'Branches, tax registration, ZATCA and document settings': 'الفروع والتسجيل الضريبي وزاتكا وإعدادات المستندات',
  'Accounts, store access, roles and who is online': 'الحسابات وصلاحيات الفروع والأدوار والمتصلون الآن',
  'Which screens each role can open and change in this store': 'الشاشات التي يمكن لكل دور فتحها وتعديلها في هذا الفرع',
  'Signature images printed on quotations, invoices and receipts': 'صور التوقيعات المطبوعة على عروض الأسعار والفواتير والإيصالات',
  'New store': 'فرع جديد', 'New user': 'مستخدم جديد', 'New role': 'دور جديد', 'New signature': 'توقيع جديد', 'Edit signature': 'تعديل التوقيع',
  'Edit role': 'تعديل الدور', 'Edit user': 'تعديل المستخدم', 'Create store': 'إنشاء الفرع', 'Create user': 'إنشاء المستخدم', 'Create role': 'إنشاء الدور',
  'Save changes': 'حفظ التغييرات', 'Discard': 'تجاهل', 'Unsaved': 'غير محفوظ', 'Unsaved changes': 'تغييرات غير محفوظة', 'All changes saved': 'تم حفظ كل التغييرات', 'No changes': 'لا توجد تغييرات',
  'Couldn’t save.': 'تعذّر الحفظ.', 'Please fix the highlighted fields.': 'يرجى تصحيح الحقول المظللة.', 'Select…': 'اختر…', 'Open': 'فتح', 'Other': 'أخرى',

  // Stores list / profile
  'Search store name…': 'ابحث باسم الفرع…', 'Active': 'نشط', 'Deleted': 'محذوف', 'All stores': 'كل الفروع', 'Branch code': 'رمز الفرع', 'Branch name': 'اسم الفرع', 'Branch': 'الفرع',
  'Email': 'البريد الإلكتروني', 'Created': 'تاريخ الإنشاء', 'Updated': 'آخر تحديث', 'Current': 'الحالي', 'Current store': 'الفرع الحالي', 'Switch to': 'التبديل إلى',
  'Switched to {{name}}': 'تم التبديل إلى {{name}}', 'Purge in {{n}}d': 'حذف نهائي خلال {{n}} يوم', 'Name (Arabic)': 'الاسم بالعربية', 'VAT no.': 'الرقم الضريبي', 'VAT %': 'نسبة الضريبة %',
  'CR no.': 'رقم السجل التجاري', 'Phone': 'الهاتف', 'Company': 'الشركة', 'Registered name': 'الاسم المسجل', 'Store name': 'اسم الفرع', 'Title': 'العنوان',
  'Business category': 'نشاط الشركة', 'Country': 'الدولة', 'National address': 'العنوان الوطني', 'Building no.': 'رقم المبنى', 'Street': 'الشارع', 'District': 'الحي', 'City': 'المدينة',
  'Zipcode': 'الرمز البريدي', 'Additional no.': 'الرقم الإضافي', 'Street (Arabic)': 'الشارع (عربي)', 'District (Arabic)': 'الحي (عربي)', 'City (Arabic)': 'المدينة (عربي)',
  'Short code': 'الرمز المختصر', 'Unit no.': 'رقم الوحدة', 'Document numbering': 'ترقيم المستندات', 'Document': 'المستند', 'Prefix': 'البادئة', 'Padding': 'عدد الخانات',
  'Starts at': 'يبدأ من', 'Example': 'مثال', 'Bank account': 'الحساب البنكي', 'Bank': 'البنك', 'Account name': 'اسم الحساب', 'Account no.': 'رقم الحساب', 'Customer no.': 'رقم العميل',
  'Record': 'السجل', 'Updated by': 'آخر تعديل بواسطة', 'Created by': 'أنشئ بواسطة', 'Phase': 'المرحلة', 'Phase 1': 'المرحلة الأولى', 'Phase 2': 'المرحلة الثانية',
  'Environment': 'البيئة', 'Connected': 'متصل', 'Not connected': 'غير متصل', 'Last connected': 'آخر اتصال', 'Last disconnected': 'آخر قطع اتصال', 'Failed attempts': 'المحاولات الفاشلة', 'Last failure': 'آخر فشل',
  'Phase 2 · Connected': 'المرحلة الثانية · متصل', 'Phase 2 · Not connected': 'المرحلة الثانية · غير متصل', 'Reconnect required': 'يلزم إعادة الربط',
  'ZATCA-sensitive fields changed. Reconnect before reporting invoices.': 'تم تغيير حقول مرتبطة بزاتكا. أعد الربط قبل إبلاغ الفواتير.',
  'Data': 'البيانات', 'Backup data': 'نسخ احتياطي للبيانات', 'Danger zone': 'منطقة الخطر', 'Delete store': 'حذف الفرع', 'Restore store': 'استعادة الفرع', 'Days': 'الأيام',
  'Purge after N days': 'حذف نهائي بعد N يوم', 'Permanent deletion in {{n}} days': 'الحذف النهائي خلال {{n}} يوم', 'Abort permanent deletion': 'إلغاء الحذف النهائي', 'Delete permanently': 'حذف نهائي',
  'Delete “{{name}}”?': 'حذف «{{name}}»؟', 'It can be restored later from the Deleted view.': 'يمكن استعادته لاحقاً من عرض المحذوفات.', 'Store deleted': 'تم حذف الفرع', 'Store restored': 'تمت استعادة الفرع',
  'Store scheduled for permanent deletion': 'تمت جدولة الفرع للحذف النهائي', 'Permanent deletion aborted': 'تم إلغاء الحذف النهائي', 'Store permanently deleted': 'تم حذف الفرع نهائياً',
  'Delete “{{name}}” permanently?': 'حذف «{{name}}» نهائياً؟', 'The store database is dropped.': 'سيتم حذف قاعدة بيانات الفرع.', 'Images and ZATCA files are removed.': 'ستتم إزالة الصور وملفات زاتكا.', 'This cannot be undone.': 'لا يمكن التراجع عن ذلك.',

  // ZATCA
  'ZATCA': 'زاتكا', 'Connect to ZATCA': 'الربط مع زاتكا', 'Reconnect to ZATCA': 'إعادة الربط مع زاتكا', 'Connect': 'ربط', 'Reconnect': 'إعادة الربط', 'Disconnect': 'قطع الاتصال',
  'OTP from ZATCA': 'رمز التحقق (OTP) من زاتكا', 'OTP is required': 'رمز التحقق مطلوب', 'OTP': 'رمز التحقق',
  'Re-connection required.': 'إعادة الربط مطلوبة.', 'ZATCA-sensitive store details were changed. Reconnect before reporting any invoice.': 'تم تغيير بيانات الفرع المرتبطة بزاتكا. أعد الربط قبل إبلاغ أي فاتورة.',
  'Generate a one-time password in the ZATCA Fatoora portal for': 'أنشئ رمز تحقق لمرة واحدة من بوابة فاتورة لـ', ', then enter it below.': '، ثم أدخله أدناه.',
  'Successfully re-connected to ZATCA!': 'تمت إعادة الربط مع زاتكا بنجاح!', 'Store connected to ZATCA successfully!': 'تم ربط الفرع مع زاتكا بنجاح!', 'Error connecting to ZATCA!': 'خطأ في الربط مع زاتكا!',
  'E-invoicing phase': 'مرحلة الفوترة الإلكترونية', 'ZATCA phase': 'مرحلة زاتكا', 'Phase 1 — generation': 'المرحلة الأولى — الإصدار', 'Phase 2 — integration': 'المرحلة الثانية — الربط والتكامل',
  'NonProduction': 'غير إنتاجية', 'Simulation': 'محاكاة', 'Production': 'إنتاج', 'Connection': 'الاتصال', 'Credentials': 'بيانات الاعتماد', 'Show credentials': 'عرض بيانات الاعتماد',
  'Read-only. Issued by ZATCA during onboarding.': 'للقراءة فقط. صادرة من زاتكا أثناء التسجيل.', 'Compliance request ID': 'رقم طلب الامتثال', 'Production request ID': 'رقم طلب الإنتاج', 'CSR': 'طلب توقيع الشهادة (CSR)',
  'Private key': 'المفتاح الخاص', 'Binary security token': 'رمز الأمان الثنائي', 'Secret': 'الرمز السري', 'Production binary security token': 'رمز الأمان الثنائي للإنتاج', 'Production secret': 'الرمز السري للإنتاج',
  'Save to switch to phase 2, then connect with an OTP.': 'احفظ للانتقال إلى المرحلة الثانية ثم اربط برمز التحقق.', 'Disconnect this store from ZATCA?': 'قطع اتصال هذا الفرع عن زاتكا؟',
  'Invoices will not be reported until you connect again.': 'لن يتم إبلاغ الفواتير حتى تعيد الربط.', 'Disconnected from ZATCA': 'تم قطع الاتصال عن زاتكا', 'Relieve from re-connect prompt': 'إلغاء تنبيه إعادة الربط',
  'Re-connect prompt cleared': 'تم إلغاء تنبيه إعادة الربط', 'ZATCA reconnection required.': 'إعادة الربط مع زاتكا مطلوبة.', 'Key store details have changed. Reconnect to ZATCA before reporting invoices.': 'تغيرت بيانات أساسية للفرع. أعد الربط مع زاتكا قبل إبلاغ الفواتير.',
  'This store is connected to ZATCA. Changing the name, branch, CR, VAT number, category or address requires reconnecting.': 'هذا الفرع مرتبط بزاتكا. تغيير الاسم أو الفرع أو السجل التجاري أو الرقم الضريبي أو النشاط أو العنوان يتطلب إعادة الربط.',
  'ZATCA last connected': 'آخر ربط مع زاتكا', 'ZATCA environment is required for phase 2': 'بيئة زاتكا مطلوبة للمرحلة الثانية',
  'ZATCA-sensitive fields changed. Please reconnect to ZATCA.': 'تم تغيير حقول مرتبطة بزاتكا. يرجى إعادة الربط مع زاتكا.',

  // Store editor sections and fields
  'Store settings sections': 'أقسام إعدادات الفرع', 'Contact': 'التواصل', 'Invoice titles': 'عناوين الفواتير', 'Preferences': 'التفضيلات', 'Print & layout': 'الطباعة والتخطيط',
  'Logo & images': 'الشعار والصور', 'Opening balances': 'الأرصدة الافتتاحية', 'WhatsApp': 'واتساب', 'Procurement & AI': 'المشتريات والذكاء الاصطناعي', 'Maintenance': 'الصيانة',
  'Legal identity': 'الهوية القانونية', 'Registered company name': 'اسم الشركة المسجل', 'Registered company name (Arabic)': 'اسم الشركة المسجل (عربي)', 'Store display name': 'اسم العرض للفرع',
  'Store display name (Arabic)': 'اسم العرض للفرع (عربي)', 'Optional — shown instead of the registered name.': 'اختياري — يظهر بدلاً من الاسم المسجل.', 'Commercial registration (CRN)': 'السجل التجاري',
  'VAT number': 'الرقم الضريبي', '15 digits, starts and ends with 3': '15 رقماً، يبدأ وينتهي بالرقم 3', 'Invoice title': 'عنوان الفاتورة', 'Invoice title (Arabic)': 'عنوان الفاتورة (عربي)',
  'Customer package': 'باقة العميل', '— No package —': '— بدون باقة —', 'Non-admin users only see the menu items in this package.': 'يرى المستخدمون غير المسؤولين عناصر القائمة في هذه الباقة فقط.',
  'Printed on invoices and sent to ZATCA.': 'يُطبع على الفواتير ويُرسل إلى زاتكا.', 'Short address code': 'رمز العنوان المختصر', 'Building number': 'رقم المبنى', 'Street name': 'اسم الشارع',
  'Street name (Arabic)': 'اسم الشارع (عربي)', 'Additional number': 'الرقم الإضافي', 'Unit number': 'رقم الوحدة', 'e.g. +966 11 456 7890': 'مثال: ‎+966 11 456 7890',
  'Printed on invoices so customers can pay by transfer.': 'يُطبع على الفواتير ليتمكن العملاء من الدفع بالتحويل.', 'Bank name': 'اسم البنك', 'Account number': 'رقم الحساب', 'IBAN': 'الآيبان', 'Customer number': 'رقم العميل',
  'Document titles': 'عناوين المستندات', 'Restore defaults': 'استعادة الافتراضي', 'Format: ENGLISH | عربي. Paid, credit (unpaid) and cash variants are chosen automatically when printing.': 'الصيغة: ENGLISH | عربي. يتم اختيار نسخة المدفوعة أو الآجلة أو النقدية تلقائياً عند الطباعة.',
  'Paid': 'مدفوعة', 'Credit': 'آجلة', 'Cash': 'نقدية', 'Quotation': 'عرض السعر', 'Delivery note': 'مذكرة التسليم', 'Stock transfer': 'نقل المخزون', 'Receivable receipt': 'إيصال القبض', 'Payable receipt': 'إيصال الصرف',
  'Phase 1 · Sales': 'المرحلة الأولى · المبيعات', 'Phase 1 · Sales returns': 'المرحلة الأولى · مرتجعات المبيعات', 'Phase 1 · Purchases': 'المرحلة الأولى · المشتريات', 'Phase 1 · Purchase returns': 'المرحلة الأولى · مرتجعات المشتريات',
  'Phase 2 · Simplified sales (B2C)': 'المرحلة الثانية · المبيعات المبسطة (للأفراد)', 'Phase 2 · Simplified credit notes': 'المرحلة الثانية · إشعارات دائنة مبسطة', 'Phase 2 · Purchases': 'المرحلة الثانية · المشتريات',
  'Phase 2 · Purchase returns': 'المرحلة الثانية · مرتجعات المشتريات', 'Phase 2 · Standard sales (B2B)': 'المرحلة الثانية · المبيعات القياسية (للشركات)', 'Phase 2 · Standard credit notes': 'المرحلة الثانية · إشعارات دائنة قياسية',
  'Phase 2 B2B · Purchases': 'المرحلة الثانية للشركات · المشتريات', 'Phase 2 B2B · Purchase returns': 'المرحلة الثانية للشركات · مرتجعات المشتريات', 'Quotation sales': 'مبيعات عروض الأسعار', 'Quotation sales returns': 'مرتجعات مبيعات عروض الأسعار',
  'Non-VAT sales': 'مبيعات بدون ضريبة', 'Non-VAT sales returns': 'مرتجعات المبيعات بدون ضريبة',
  'Codes are generated as PREFIX-0001. Start numbers lock once documents exist.': 'تُنشأ الأرقام بالشكل PREFIX-0001. يُقفل رقم البداية بعد إنشاء مستندات.', 'Locked': 'مقفل', 'Locked — documents already exist': 'مقفل — توجد مستندات بالفعل',
  'Sales': 'المبيعات', 'Sales returns': 'مرتجعات المبيعات', 'Purchases': 'المشتريات', 'Purchase returns': 'مرتجعات المشتريات', 'Purchase orders': 'أوامر الشراء', 'Purchase requests': 'طلبات الشراء',
  'Quotations': 'عروض الأسعار', 'Delivery notes': 'مذكرات التسليم', 'Stock transfers': 'تحويلات المخزون', 'Customers': 'العملاء', 'Vendors': 'الموردون', 'Expenses': 'المصروفات',
  'Receivables': 'المقبوضات', 'Payables': 'المدفوعات', 'Capital': 'رأس المال', 'Drawings': 'المسحوبات', 'RFQ': 'طلبات عروض الأسعار',
  'Invoice & display': 'الفواتير والعرض', 'Sales & purchasing': 'المبيعات والمشتريات', 'Modules & features': 'الوحدات والميزات', 'Accounting & financials': 'المحاسبة والمالية', 'Dashboards': 'لوحات المعلومات', 'System': 'النظام',
  'Show the Saudi riyal symbol on invoices': 'إظهار رمز الريال السعودي على الفواتير', 'Show seller info first on invoice previews': 'إظهار بيانات البائع أولاً في معاينة الفواتير', 'Show address in invoice footer': 'إظهار العنوان في تذييل الفاتورة',
  'Show “Received by” footer on invoices': 'إظهار تذييل «المستلم» على الفواتير', 'Show “Created by” next to remarks on previews': 'إظهار «أنشئ بواسطة» بجانب الملاحظات في المعاينة', 'Place the ZATCA QR code at the bottom left': 'وضع رمز QR الخاص بزاتكا أسفل اليسار',
  'Report receivables to ZATCA as debit notes': 'إبلاغ المقبوضات لزاتكا كإشعارات مدينة', 'Report payables to ZATCA as credit notes': 'إبلاغ المدفوعات لزاتكا كإشعارات دائنة', 'Lock sales once reported to ZATCA': 'قفل المبيعات بعد إبلاغها لزاتكا',
  'Suggest linking advance payments on sales': 'اقتراح ربط الدفعات المقدمة بالمبيعات', 'Show VAT on receivables and payables': 'إظهار الضريبة في المقبوضات والمدفوعات', 'Let users choose the print type on previews': 'السماح باختيار نوع الطباعة في المعاينة',
  'One-line product names on invoices': 'أسماء المنتجات في سطر واحد على الفواتير', 'One-line product names on printed invoices': 'أسماء المنتجات في سطر واحد على الفواتير المطبوعة', 'Show prices on delivery notes': 'إظهار الأسعار في مذكرات التسليم',
  'Skip product selection when importing a delivery note': 'تخطي اختيار المنتجات عند استيراد مذكرة تسليم', 'Exclude purchases from P&L and dashboards': 'استبعاد المشتريات من الأرباح والخسائر ولوحات المعلومات',
  'Block sale when the selling price is below cost': 'منع البيع عندما يكون سعر البيع أقل من التكلفة', 'Auto-close sales payments on purchase': 'إغلاق دفعات المبيعات تلقائياً عند الشراء', 'Auto-close purchase payments on sales': 'إغلاق دفعات المشتريات تلقائياً عند البيع',
  'Auto-close payments on returns': 'إغلاق الدفعات تلقائياً عند الإرجاع', 'Allow adjusting same-date payments': 'السماح بتعديل دفعات نفس التاريخ', 'Block sales after this many unpaid invoices (0 = off)': 'منع البيع بعد هذا العدد من الفواتير غير المدفوعة (0 = معطل)',
  'Products': 'المنتجات', 'Services': 'الخدمات', 'Warehouses & stock transfers': 'المستودعات وتحويلات المخزون', 'Workshop (automobile) module': 'وحدة الورشة (السيارات)', 'Employees & salaries': 'الموظفون والرواتب',
  'Allow manual sales invoice numbers': 'السماح بترقيم يدوي لفواتير المبيعات', 'Sales page selection': 'اختيار صفحة المبيعات', 'Notifications bell': 'جرس الإشعارات', 'Auto-translate names to Arabic': 'ترجمة الأسماء تلقائياً إلى العربية',
  'Right-to-left layout for Arabic': 'اتجاه من اليمين لليسار للعربية', 'Arabic names list on the product form': 'قائمة الأسماء العربية في نموذج المنتج', 'Allow duplicate products by default': 'السماح بتكرار المنتجات افتراضياً',
  'Customer PO number on sales': 'رقم أمر شراء العميل في المبيعات', 'Validate purchase unit price on quotations': 'التحقق من سعر الشراء في عروض الأسعار', 'Update wholesale & retail prices from last purchase (using margin %)': 'تحديث أسعار الجملة والتجزئة من آخر شراء (باستخدام نسبة الهامش)',
  'Show minus sign on liability balances': 'إظهار إشارة السالب على أرصدة الالتزامات', 'Hide the total row in the balance sheet': 'إخفاء صف الإجمالي في الميزانية', 'Post quotation invoices to the ledger': 'ترحيل فواتير عروض الأسعار إلى دفتر الأستاذ',
  'Sales from quotations (quotation sales returns)': 'المبيعات من عروض الأسعار (مرتجعاتها)', 'Business dashboard': 'لوحة الأعمال', 'Workshop dashboard': 'لوحة الورشة', 'Statistics: overall summary': 'الإحصائيات: الملخص العام',
  'Statistics: profit & loss statement': 'الإحصائيات: قائمة الأرباح والخسائر', 'VAT card on dashboards': 'بطاقة الضريبة في لوحات المعلومات', 'Update stock on quotation sales': 'تحديث المخزون عند مبيعات عروض الأسعار',
  'Reset document serials every month': 'إعادة ترقيم المستندات كل شهر', 'No tax for quotation invoices & quotation sales returns': 'بدون ضريبة لفواتير عروض الأسعار ومرتجعاتها', 'Default quotation validity (days)': 'صلاحية عرض السعر الافتراضية (أيام)',
  'Default delivery (days)': 'مدة التسليم الافتراضية (أيام)', 'Prompt users to refresh when a new version is deployed': 'تنبيه المستخدمين للتحديث عند نشر إصدار جديد', 'Sync menu settings to the server': 'مزامنة إعدادات القائمة مع الخادم',
  'Sync print preview settings to the server': 'مزامنة إعدادات معاينة الطباعة مع الخادم', 'Layouts': 'التخطيطات', 'Choose the layout used for previews, PDFs and entry forms.': 'اختر التخطيط المستخدم للمعاينات وملفات PDF ونماذج الإدخال.',
  'A4 invoice layout': 'تخطيط فاتورة A4', 'Preview toolbar': 'شريط أدوات المعاينة', 'Balance sheet': 'الميزانية', 'Balance sheet A4 preview': 'معاينة الميزانية A4', 'Balance sheet toolbar': 'شريط أدوات الميزانية',
  'Sales form': 'نموذج المبيعات', 'Sales return form': 'نموذج مرتجع المبيعات', 'Purchase form': 'نموذج المشتريات', 'Purchase return form': 'نموذج مرتجع المشتريات', 'Quotation form': 'نموذج عرض السعر', 'Quotation sales return form': 'نموذج مرتجع مبيعات عرض السعر',
  'Type 1': 'النوع 1', 'Type 2': 'النوع 2', 'Type 3': 'النوع 3', 'Type 4': 'النوع 4', 'Type 5': 'النوع 5', 'Classic': 'كلاسيكي', 'Classic professional': 'كلاسيكي احترافي', 'Sales return — compact': 'مرتجع المبيعات — مضغوط',
  'Standard': 'قياسي', 'Modern dark toolbar': 'شريط أدوات داكن حديث', 'Classic ledger': 'دفتر كلاسيكي', 'Modern professional': 'احترافي حديث', 'VAN store': 'متجر متنقل', 'Workshop': 'ورشة',
  'Server copies': 'النسخ على الخادم', 'Used when syncing is switched on above.': 'تُستخدم عند تفعيل المزامنة أعلاه.', 'items stored': 'عنصر محفوظ', 'Upload my menu': 'رفع قائمتي', 'Menu settings uploaded': 'تم رفع إعدادات القائمة',
  'Server menu cleared': 'تم مسح القائمة على الخادم', 'Print settings': 'إعدادات الطباعة', 'documents customised': 'مستندات مخصصة', 'Server print settings cleared': 'تم مسح إعدادات الطباعة على الخادم', 'Reset': 'إعادة تعيين', 'Clear': 'مسح',
  'Logo': 'الشعار', 'Store logo': 'شعار الفرع', 'Recommended 300×100 px transparent PNG, up to 500 KB.': 'يُفضّل PNG شفاف بمقاس 300×100 بكسل وحتى 500 كيلوبايت.', 'Remove the logo?': 'إزالة الشعار؟', 'Remove': 'إزالة',
  'Invoice background': 'خلفية الفاتورة', 'Invoice background image': 'صورة خلفية الفاتورة', 'A4 at 150 dpi (1240×1754 px) or 595×842 px, PNG or JPG, up to 2 MB.': 'A4 بدقة 150 نقطة (1240×1754 بكسل) أو 595×842 بكسل، PNG أو JPG، حتى 2 ميجابايت.',
  'Remove the invoice background?': 'إزالة خلفية الفاتورة؟', 'No image': 'لا توجد صورة', 'Not saved yet': 'لم يُحفظ بعد', 'Change': 'تغيير', 'Upload': 'رفع', 'Choose an image file.': 'اختر ملف صورة.', 'File is too large (max {{n}}).': 'الملف كبير جداً (الحد الأقصى {{n}}).',
  'Posted to the ledger when saved. Amounts must be 0 or more; a date is required for any amount.': 'تُرحّل إلى دفتر الأستاذ عند الحفظ. يجب أن تكون المبالغ 0 أو أكثر، والتاريخ مطلوب لأي مبلغ.',
  'Cash opening balance': 'الرصيد الافتتاحي للنقدية', 'Bank opening balance': 'الرصيد الافتتاحي للبنك', 'As of': 'بتاريخ',
  'WhatsApp (Evolution API)': 'واتساب (Evolution API)', 'Send invoices as PDF attachments from your own WhatsApp number instead of a link.': 'إرسال الفواتير كمرفقات PDF من رقم واتساب الخاص بك بدلاً من رابط.',
  'Send documents through the connected WhatsApp number': 'إرسال المستندات عبر رقم واتساب المرتبط', 'Evolution API URL': 'رابط Evolution API', 'Evolution API key': 'مفتاح Evolution API', 'Instance name': 'اسم النسخة',
  'Save your changes before connecting.': 'احفظ تغييراتك قبل الربط.', 'Couldn’t reach the WhatsApp service.': 'تعذّر الوصول إلى خدمة واتساب.', '{{n}} contacts': '{{n}} جهة اتصال', 'Sync contacts': 'مزامنة جهات الاتصال',
  'Clear contacts': 'مسح جهات الاتصال', 'Synced {{n}} contacts': 'تمت مزامنة {{n}} جهة اتصال', 'Contacts cleared': 'تم مسح جهات الاتصال', 'Clear synced contacts?': 'مسح جهات الاتصال المتزامنة؟',
  'WhatsApp QR code': 'رمز QR لواتساب', 'Waiting for QR code…': 'بانتظار رمز QR…', 'Open WhatsApp → Linked devices → Link a device, and scan this code.': 'افتح واتساب ← الأجهزة المرتبطة ← ربط جهاز، ثم امسح هذا الرمز.',
  'WhatsApp number': 'رقم واتساب', 'With country code, e.g. 966501234567': 'مع رمز الدولة، مثال: 966501234567', 'Connect WhatsApp': 'ربط واتساب', 'WhatsApp connected successfully!': 'تم ربط واتساب بنجاح!',
  'Disconnect WhatsApp from “{{name}}”?': 'فصل واتساب عن «{{name}}»؟', 'This deletes the Evolution API instance.': 'سيؤدي ذلك إلى حذف نسخة Evolution API.', 'WhatsApp disconnected': 'تم فصل واتساب',
  'Procurement & AI settings': 'إعدادات المشتريات والذكاء الاصطناعي', 'The AI RFQ bot, procurement WhatsApp, purchase-bill tracking, email accounts & signatures, Google, RFQ and AI model settings are managed in the procurement workspace.': 'تُدار إعدادات روبوت طلبات الأسعار وواتساب المشتريات وتتبع فواتير الشراء وحسابات البريد والتواقيع وجوجل وطلبات الأسعار ونماذج الذكاء الاصطناعي من مساحة المشتريات.',
  'WhatsApp bot': 'روبوت واتساب', 'Purchase bills': 'فواتير الشراء', 'Email settings': 'إعدادات البريد', 'Google settings': 'إعدادات جوجل', 'RFQ settings': 'إعدادات طلبات الأسعار', 'AI models': 'نماذج الذكاء الاصطناعي', 'Open procurement settings': 'فتح إعدادات المشتريات',
  'Test data': 'بيانات تجريبية', 'Fill the store with realistic sample records for training or demos.': 'تعبئة الفرع بسجلات تجريبية واقعية للتدريب أو العروض.', 'Populate test data': 'إضافة بيانات تجريبية', 'Add test data': 'إضافة البيانات التجريبية',
  'Add sample data to “{{name}}”?': 'إضافة بيانات تجريبية إلى «{{name}}»؟', 'Creates demo customers, vehicles, technicians, products and repair jobs.': 'ينشئ عملاء ومركبات وفنيين ومنتجات وأوامر إصلاح تجريبية.',
  'Test data added: {{c}} customers, {{v}} vehicles, {{te}} technicians, {{p}} products, {{j}} repair jobs': 'تمت إضافة البيانات: {{c}} عميل، {{v}} مركبة، {{te}} فني، {{p}} منتج، {{j}} أمر إصلاح',
  'Delete every document of this store while keeping its settings.': 'حذف كل مستندات هذا الفرع مع الاحتفاظ بالإعدادات.', 'Clear data': 'مسح البيانات', 'Clear all data of “{{name}}”?': 'مسح كل بيانات «{{name}}»؟', 'Continue': 'متابعة',
  'Every sale, purchase, product, customer and ledger entry of this store will be deleted. Settings are kept.': 'سيتم حذف كل المبيعات والمشتريات والمنتجات والعملاء وقيود الأستاذ لهذا الفرع. ستبقى الإعدادات.',
  'This cannot be undone. Really clear the data?': 'لا يمكن التراجع. هل تريد فعلاً مسح البيانات؟', 'Store data cleared ({{n}} collections dropped)': 'تم مسح بيانات الفرع (حذف {{n}} مجموعة)',
  'Only administrators and managers can change store settings.': 'يمكن للمسؤولين والمدراء فقط تغيير إعدادات الفرع.', 'Store created successfully!': 'تم إنشاء الفرع بنجاح!', 'Store updated successfully!': 'تم تحديث الفرع بنجاح!',
  'Failed to save store. Please fix the errors and try again.': 'تعذّر حفظ الفرع. يرجى تصحيح الأخطاء والمحاولة مرة أخرى.', '{{n}} errors': '{{n}} أخطاء',
  'Supply Activities': 'أنشطة التوريد', 'Service Activities': 'أنشطة الخدمات', 'Retail': 'التجزئة', 'Food and Beverages': 'الأغذية والمشروبات', 'Trading': 'التجارة', 'Manufacturing': 'التصنيع', 'Healthcare': 'الرعاية الصحية',
  'Real Estate': 'العقارات', 'Construction': 'البناء', 'Transportation': 'النقل', 'Technology': 'التقنية', 'Education': 'التعليم', 'Financial Services': 'الخدمات المالية',

  // Validation messages
  'Business category is required': 'نشاط الشركة مطلوب', 'Name is required': 'الاسم مطلوب', 'Name in arabic is required': 'الاسم بالعربية مطلوب', 'Branch code is required': 'رمز الفرع مطلوب', 'Branch name is required': 'اسم الفرع مطلوب',
  'Phone is required': 'الهاتف مطلوب', 'CRN is required': 'السجل التجاري مطلوب', 'CRN should be alpha numeric(a-zA-Z0-9)': 'يجب أن يتكون السجل التجاري من أحرف وأرقام إنجليزية فقط', 'VAT No is required': 'الرقم الضريبي مطلوب',
  'VAT No should be 15 digits': 'يجب أن يكون الرقم الضريبي 15 رقماً', 'VAT No should start and end with 3': 'يجب أن يبدأ الرقم الضريبي وينتهي بالرقم 3', 'VAT % is required': 'نسبة الضريبة مطلوبة', 'E-mail is required': 'البريد الإلكتروني مطلوب',
  'E-mail is not valid': 'البريد الإلكتروني غير صالح', 'Country is required': 'الدولة مطلوبة', 'Building number is required': 'رقم المبنى مطلوب', 'Building number should be 4 digits': 'يجب أن يكون رقم المبنى 4 أرقام',
  'Street name is required': 'اسم الشارع مطلوب', 'Street name in arabic is required': 'اسم الشارع بالعربية مطلوب', 'District name is required': 'اسم الحي مطلوب', 'District name in arabic is required': 'اسم الحي بالعربية مطلوب',
  'City name is required': 'اسم المدينة مطلوب', 'City name in arabic is required': 'اسم المدينة بالعربية مطلوب', 'Zipcode is required': 'الرمز البريدي مطلوب', 'Zipcode should be 5 digits': 'يجب أن يكون الرمز البريدي 5 أرقام',
  'Prefix is required': 'البادئة مطلوبة', 'Padding must be greater than 0': 'يجب أن يكون عدد الخانات أكبر من 0', 'Start must be 0 or more': 'يجب أن تكون البداية 0 أو أكثر', 'Must be greater than 0': 'يجب أن يكون أكبر من 0',
  'Opening balance cannot be negative': 'لا يمكن أن يكون الرصيد الافتتاحي سالباً', 'Date is required when an opening balance is entered': 'التاريخ مطلوب عند إدخال رصيد افتتاحي',
  'Opening balance date is required when an opening balance is entered': 'تاريخ الرصيد الافتتاحي مطلوب عند إدخال رصيد', 'Mob is required': 'رقم الجوال مطلوب', 'Password is required': 'كلمة المرور مطلوبة',
  'Must be at least 6 characters': 'يجب ألا تقل عن 6 أحرف', 'Current password is required': 'كلمة المرور الحالية مطلوبة', 'New password is required': 'كلمة المرور الجديدة مطلوبة', 'Please confirm your new password': 'يرجى تأكيد كلمة المرور الجديدة',
  'Passwords do not match': 'كلمتا المرور غير متطابقتين', 'Role name is required': 'اسم الدور مطلوب', 'Signature is required': 'التوقيع مطلوب', 'Store name is required': 'اسم الفرع مطلوب',

  // Backup / duplicate jobs
  'Backup store': 'نسخ احتياطي للفرع', 'Duplicate store': 'نسخ الفرع', 'Duplicate store (all data)': 'نسخ الفرع (كل البيانات)', 'Duplicate with products': 'نسخ مع المنتجات', 'Duplicate with products (no images)': 'نسخ مع المنتجات (بدون صور)',
  'Duplicate without data': 'نسخ بدون بيانات', 'Copies every document, image and ZATCA file into a new store.': 'ينسخ كل المستندات والصور وملفات زاتكا إلى فرع جديد.',
  'Copies the store settings plus the product catalogue (categories, brands, products, images).': 'ينسخ إعدادات الفرع مع كتالوج المنتجات (الفئات والعلامات والمنتجات والصور).',
  'Same as above but without product images.': 'مثل السابق لكن بدون صور المنتجات.', 'Copies only the store settings into an empty store.': 'ينسخ إعدادات الفرع فقط إلى فرع فارغ.',
  'Size': 'الحجم', 'Calculating…': 'جارٍ الحساب…', 'Total': 'الإجمالي', 'Store database': 'قاعدة بيانات الفرع', 'Store record': 'سجل الفرع', 'Images': 'الصور', 'ZATCA files': 'ملفات زاتكا', 'Product catalogue': 'كتالوج المنتجات',
  'New store name': 'اسم الفرع الجديد', 'New store name (Arabic)': 'اسم الفرع الجديد (عربي)', 'The copy keeps the {{env}} ZATCA environment but is marked as not connected and all ZATCA credentials are cleared.': 'تحتفظ النسخة ببيئة زاتكا {{env}} لكنها تُعلَّم كغير متصلة وتُمسح كل بيانات اعتماد زاتكا.',
  'Overall': 'الإجمالي', 'Elapsed': 'المنقضي', 'ETA': 'المتبقي', 'Completed in': 'اكتمل خلال', 'Start backup': 'بدء النسخ الاحتياطي', 'Start duplicate': 'بدء النسخ', 'Backup again': 'نسخ احتياطي مرة أخرى', 'Download again': 'تنزيل مرة أخرى',
  'Backup complete — your download has started.': 'اكتمل النسخ الاحتياطي — بدأ التنزيل.', 'Store duplicated successfully!': 'تم نسخ الفرع بنجاح!',

  // Users
  'All users': 'كل المستخدمين', 'Online now': 'متصل الآن', 'Online': 'متصل', 'Offline': 'غير متصل', 'Status': 'الحالة', 'Name': 'الاسم', 'Mobile': 'الجوال', 'Devices': 'الأجهزة', 'Device': 'جهاز',
  'Computers · mobiles · tabs': 'حواسيب · جوالات · تبويبات', 'Search name, email or mobile…': 'ابحث بالاسم أو البريد أو الجوال…', 'Manager': 'مدير', 'Salesman': 'مندوب مبيعات', 'SalesMan': 'مندوب مبيعات',
  'All stores (administrator)': 'كل الفروع (مسؤول)', 'No stores assigned': 'لا توجد فروع مسندة', 'Inactive': 'غير نشط', 'Change password': 'تغيير كلمة المرور', 'Activate': 'تفعيل', 'Deactivate': 'إيقاف',
  'Activate {{name}}?': 'تفعيل {{name}}؟', 'Deactivate {{name}}?': 'إيقاف {{name}}؟', 'They will be signed out and can’t sign in until re-activated.': 'سيتم تسجيل خروجه ولن يتمكن من الدخول حتى إعادة التفعيل.',
  'User activated': 'تم تفعيل المستخدم', 'User deactivated': 'تم إيقاف المستخدم', 'Delete {{name}}?': 'حذف {{name}}؟', 'The account is removed from the user list.': 'تتم إزالة الحساب من قائمة المستخدمين.', 'User deleted': 'تم حذف المستخدم',
  'All': 'الكل', 'Opening balance': 'الرصيد الافتتاحي', 'Direction': 'الاتجاه', 'User owes store': 'المستخدم مدين للفرع', 'Store owes user': 'الفرع مدين للمستخدم', 'Posted': 'مُرحّل',
  'Access': 'الصلاحيات', 'RBAC roles': 'أدوار الصلاحيات', 'No devices yet': 'لا توجد أجهزة بعد', 'Devices appear after the user signs in to the new app.': 'تظهر الأجهزة بعد تسجيل دخول المستخدم إلى التطبيق الجديد.',
  'Show all {{n}} devices': 'عرض كل الأجهزة ({{n}})', 'Platform': 'المنصة', 'Screen': 'الشاشة', 'Touch': 'لمس', 'Battery': 'البطارية', 'Unknown': 'غير معروف', 'Tabs open': 'التبويبات المفتوحة',
  'Change password for {{name}}': 'تغيير كلمة مرور {{name}}', 'No current password required.': 'لا حاجة لكلمة المرور الحالية.', 'Current password': 'كلمة المرور الحالية', 'New password': 'كلمة المرور الجديدة',
  'Confirm new password': 'تأكيد كلمة المرور الجديدة', 'Passwords match': 'كلمتا المرور متطابقتان', 'Strength': 'القوة', 'Weak': 'ضعيفة', 'Fair': 'مقبولة', 'Good': 'جيدة', 'Strong': 'قوية',
  'Password changed successfully!': 'تم تغيير كلمة المرور بنجاح!', 'Account': 'الحساب', 'Password': 'كلمة المرور', 'At least 6 characters.': '6 أحرف على الأقل.', 'Leave blank to keep the current password.': 'اتركها فارغة للإبقاء على كلمة المرور الحالية.',
  'You cannot change your own role.': 'لا يمكنك تغيير دورك.', 'Admins see every store; managers and salesmen only their assigned stores.': 'يرى المسؤولون كل الفروع، والمدراء والمندوبون الفروع المسندة إليهم فقط.',
  '{{n}} selected': '{{n}} محدد', 'Search stores…': 'ابحث في الفروع…', 'Search stores': 'البحث في الفروع', 'No stores found': 'لا توجد فروع', 'No roles assigned': 'لا توجد أدوار مسندة', 'Add role': 'إضافة دور', 'Add role…': 'إضافة دور…',
  'Already posted to the ledger — changes adjust the posting.': 'تم الترحيل بالفعل — التغييرات تعدّل القيد.', 'Optional. Money owed between the store and this user when they start.': 'اختياري. المبالغ المستحقة بين الفرع وهذا المستخدم عند البدء.',
  'Amount': 'المبلغ', 'User created successfully!': 'تم إنشاء المستخدم بنجاح!', 'User updated successfully!': 'تم تحديث المستخدم بنجاح!', 'Failed to process user!': 'تعذّرت معالجة المستخدم!',

  // Roles
  'Search role name…': 'ابحث باسم الدور…', '{{n}} resources': '{{n}} شاشة', 'No roles yet. Create one to grant non-admin users access to specific screens.': 'لا توجد أدوار بعد. أنشئ دوراً لمنح المستخدمين غير المسؤولين صلاحية شاشات محددة.',
  'Delete role “{{name}}”?': 'حذف الدور «{{name}}»؟', 'Role deleted': 'تم حذف الدور', 'Role created': 'تم إنشاء الدور', 'Role updated': 'تم تحديث الدور', 'Permissions': 'الصلاحيات', 'Read': 'عرض', 'Create': 'إنشاء', 'Update': 'تعديل', 'Delete': 'حذف',
  'All {{action}}': 'كل {{action}}', 'Grant everything': 'منح كل الصلاحيات', 'Role name': 'اسم الدور', 'e.g. Sales Manager': 'مثال: مدير المبيعات',
  'Read lets users open a screen; create, update and delete control the actions on it. Granting an action also grants read.': 'العرض يتيح فتح الشاشة؛ والإنشاء والتعديل والحذف تتحكم في الإجراءات عليها. منح أي إجراء يمنح العرض تلقائياً.',

  // Signatures
  'Search signature name…': 'ابحث باسم التوقيع…', 'Signature image': 'صورة التوقيع', 'A transparent PNG of the handwritten signature works best.': 'يُفضّل استخدام صورة PNG شفافة للتوقيع.', 'e.g. Sales manager': 'مثال: مدير المبيعات',
  'Delete signature “{{name}}”?': 'حذف التوقيع «{{name}}»؟', 'Signature deleted': 'تم حذف التوقيع',

  // Menu settings
  'Drag or use the arrows to reorder, switch to show or hide. Changes are saved automatically. The first visible item opens after sign-in.': 'اسحب أو استخدم الأسهم لإعادة الترتيب، واستخدم المفتاح للإظهار أو الإخفاء. تُحفظ التغييرات تلقائياً. يُفتح أول عنصر ظاهر بعد تسجيل الدخول.',
  'Menu reset': 'تمت إعادة تعيين القائمة', 'Server sync failed:': 'فشلت المزامنة مع الخادم:', 'At least one item must be visible.': 'يجب أن يكون عنصر واحد على الأقل ظاهراً.', 'Menu items': 'عناصر القائمة',
  'Landing': 'صفحة البداية', 'Set landing': 'تعيين كصفحة البداية', 'Move up': 'تحريك لأعلى', 'Move down': 'تحريك لأسفل', 'Show': 'إظهار',
  'Your menu is synced to this store on the server.': 'قائمتك متزامنة مع هذا الفرع على الخادم.', 'Your menu is saved on this device only. An administrator can enable server sync in store settings → Print & layout.': 'قائمتك محفوظة على هذا الجهاز فقط. يمكن للمسؤول تفعيل المزامنة من إعدادات الفرع ← الطباعة والتخطيط.',
};
