// Arabic strings for the procurement module, keyed by the English source text.
export const ar: Record<string, string> = {
  "(no subject)": "(بدون موضوع)",
  "(pending authorisation)": "(بانتظار التفويض)",
  "0 keeps messages forever.": "0 يحتفظ بالرسائل دائمًا.",
  "AI RFQ bot": "بوت طلبات الأسعار بالذكاء الاصطناعي",
  "AI categorisation skipped (no LLM key configured).": "تم تخطي التصنيف بالذكاء الاصطناعي (لا يوجد مفتاح نموذج لغوي).",
  "AI categorizing": "التصنيف بالذكاء الاصطناعي",
  "AI extraction": "الاستخراج بالذكاء الاصطناعي",
  "AI extracts prices from the text in the background (needs an LLM key).": "يستخرج الذكاء الاصطناعي الأسعار من النص في الخلفية (يتطلب مفتاح نموذج لغوي).",
  "AI is analysing the RFQ…": "الذكاء الاصطناعي يحلل طلب عرض السعر…",
  "AI model API keys": "مفاتيح API لنماذج الذكاء الاصطناعي",
  "AI models": "نماذج الذكاء الاصطناعي",
  "AI models per task": "نماذج الذكاء الاصطناعي لكل مهمة",
  "AI procurement": "المشتريات الذكية",
  "AI provider": "مزود الذكاء الاصطناعي",
  "AI skipped": "تم تخطي الذكاء الاصطناعي",
  "API key": "مفتاح API",
  "API keys come from the AI models tab.": "تؤخذ مفاتيح API من تبويب نماذج الذكاء الاصطناعي.",
  "Accept only emails containing": "قبول الرسائل التي تحتوي فقط على",
  "Access key ID": "معرّف مفتاح الوصول",
  "Access token": "رمز الوصول",
  "Account settings saved": "تم حفظ إعدادات الحساب",
  "Active": "نشط",
  "Active (include in RFQ forwarding)": "نشط (يُضمَّن في إرسال طلبات الأسعار)",
  "Add a key for at least one provider to enable AI extraction of RFQs and supplier quotations. Keys are saved with the store settings.": "أضف مفتاحًا لمزود واحد على الأقل لتفعيل استخراج طلبات الأسعار وعروض الموردين بالذكاء الاصطناعي. تُحفظ المفاتيح مع إعدادات الفرع.",
  "Add account": "إضافة حساب",
  "Add email account": "إضافة حساب بريد",
  "Add from catalog": "إضافة من الكتالوج",
  "Add prices to RFQ": "إضافة الأسعار إلى طلب عرض السعر",
  "Add products, upload a file, or enter a description.": "أضف منتجات أو ارفع ملفًا أو أدخل وصفًا.",
  "Add purchase markets in Procurement settings → Google": "أضف أسواق الشراء من إعدادات المشتريات ← جوجل",
  "Add purchase markets on the Google tab first.": "أضف أسواق الشراء من تبويب جوجل أولًا.",
  "Add quotation": "إضافة عرض سعر",
  "Add quotation prices to RFQ": "إضافة أسعار العرض إلى طلب عرض السعر",
  "Add reply": "إضافة رد",
  "Add row": "إضافة سطر",
  "Add signature": "إضافة توقيع",
  "Add supplier": "إضافة مورد",
  "Add supplier reply": "إضافة رد مورد",
  "Add suppliers below or fetch them from Google Maps.": "أضف الموردين أدناه أو اجلبهم من خرائط جوجل.",
  "Add suppliers manually, fetch them from Google Maps on an RFQ, or populate them from your vendors in Procurement settings.": "أضف الموردين يدويًا أو اجلبهم من خرائط جوجل في طلب عرض سعر أو استوردهم من مورديك في إعدادات المشتريات.",
  "Add this number": "إضافة هذا الرقم",
  "Added {{n}} prices to {{code}}": "تمت إضافة {{n}} سعرًا إلى {{code}}",
  "Additional description / enquiry text": "وصف إضافي / نص الاستفسار",
  "Additional detail files": "ملفات تفاصيل إضافية",
  "Address": "العنوان",
  "All": "الكل",
  "All directions": "كل الاتجاهات",
  "All emails with {{e}} will be deleted.": "سيتم حذف جميع الرسائل مع {{e}}.",
  "All messages": "كل الرسائل",
  "Allowed WhatsApp senders": "مرسلو واتساب المسموح لهم",
  "Allowed senders": "المرسلون المسموح لهم",
  "Any": "أي",
  "Attach file": "إرفاق ملف",
  "Attachment uploaded": "تم رفع المرفق",
  "Attachments": "المرفقات",
  "Attachments downloaded": "تم تنزيل المرفقات",
  "Authorise": "تفويض",
  "Auto-delete messages after (days)": "حذف الرسائل تلقائيًا بعد (أيام)",
  "Auto-filled from website if left blank": "يُملأ تلقائيًا من الموقع إذا تُرك فارغًا",
  "Automatic RFQ creation": "الإنشاء التلقائي لطلبات الأسعار",
  "Back": "رجوع",
  "Back to conversations": "العودة إلى المحادثات",
  "Backfill emails": "استكمال البريد الإلكتروني",
  "Bot WhatsApp number": "رقم واتساب البوت",
  "Callback URL": "رابط الاستدعاء",
  "Cancel": "إلغاء",
  "Cancelled": "ملغى",
  "Capture the customer’s request, review the extracted items, then send it to suppliers.": "سجّل طلب العميل وراجع البنود المستخرجة ثم أرسله إلى الموردين.",
  "Catalog": "الكتالوج",
  "Catalog: {{l}} linked, {{c}} created": "الكتالوج: {{l}} مرتبط، {{c}} تم إنشاؤه",
  "Categories": "الفئات",
  "Categories decide which RFQs this supplier receives. Press Enter to add.": "تحدد الفئات طلبات الأسعار التي يستلمها هذا المورد. اضغط Enter للإضافة.",
  "Categories drive matching: an RFQ is sent to active suppliers whose categories match the RFQ’s AI-identified categories.": "تعتمد المطابقة على الفئات: يُرسل طلب عرض السعر إلى الموردين النشطين الذين تطابق فئاتهم الفئات التي حددها الذكاء الاصطناعي.",
  "Categories identified": "تم تحديد الفئات",
  "Categories identified — searching suppliers…": "تم تحديد الفئات — جارٍ البحث عن موردين…",
  "Categorises your vendors with AI, looks them up on Google Maps and adds them as RFQ suppliers.": "يصنّف مورديك بالذكاء الاصطناعي ويبحث عنهم في خرائط جوجل ويضيفهم كموردي طلبات أسعار.",
  "Category": "الفئة",
  "Category error": "خطأ في الفئة",
  "Check numbers on WhatsApp": "التحقق من الأرقام على واتساب",
  "Choose a template": "اختر قالبًا",
  "Choose at least one file to extract from.": "اختر ملفًا واحدًا على الأقل للاستخراج منه.",
  "Choose at least one quotation file.": "اختر ملف عرض سعر واحدًا على الأقل.",
  "Cities where you buy": "المدن التي تشتري منها",
  "City": "المدينة",
  "Classification": "التصنيف",
  "Clear all": "مسح الكل",
  "Client ID": "معرّف العميل",
  "Client secret": "سر العميل",
  "Close": "إغلاق",
  "Cloudflare account ID": "معرّف حساب Cloudflare",
  "Company": "الشركة",
  "Connect": "ربط",
  "Connect an email account in Procurement settings, then press Sync now.": "اربط حساب بريد في إعدادات المشتريات ثم اضغط مزامنة الآن.",
  "Connect the WhatsApp Cloud API number that receives RFQs and sends them to suppliers (Meta Business → WhatsApp → API setup).": "اربط رقم WhatsApp Cloud API الذي يستقبل طلبات الأسعار ويرسلها إلى الموردين (Meta Business ← WhatsApp ← إعداد API).",
  "Connect the bot WhatsApp number and choose the \"RFQ to Supplier\" template in": "اربط رقم واتساب البوت واختر قالب \"طلب عرض سعر للمورد\" في",
  "Connect the mailbox where customers send RFQs and suppliers send quotations.": "اربط صندوق البريد الذي يرسل إليه العملاء طلبات الأسعار ويرسل إليه الموردون عروضهم.",
  "Connected": "متصل",
  "Connected {{e}}": "تم ربط {{e}}",
  "Connected {{p}}": "تم ربط {{p}}",
  "Contact": "جهة الاتصال",
  "Contact details": "تفاصيل جهة الاتصال",
  "Content": "المحتوى",
  "Content extraction test": "اختبار استخراج المحتوى",
  "Content is HTML": "المحتوى بصيغة HTML",
  "Conversation deleted": "تم حذف المحادثة",
  "Conversations": "المحادثات",
  "Copied": "تم النسخ",
  "Copy": "نسخ",
  "Copy failed": "فشل النسخ",
  "Create OAuth credentials with redirect URI": "أنشئ بيانات اعتماد OAuth برابط إعادة التوجيه",
  "Create RFQ": "إنشاء طلب عرض سعر",
  "Create RFQ suppliers from purchases": "إنشاء موردي طلبات الأسعار من المشتريات",
  "Create RFQs automatically from incoming WhatsApp": "إنشاء طلبات الأسعار تلقائيًا من رسائل واتساب الواردة",
  "Create RFQs automatically from incoming email": "إنشاء طلبات الأسعار تلقائيًا من البريد الوارد",
  "Create quotation": "إنشاء عرض سعر",
  "Created": "تاريخ الإنشاء",
  "Currency": "العملة",
  "Custom market": "سوق مخصص",
  "Customer": "العميل",
  "Customer RFQ ID": "رقم طلب العميل",
  "Customer RFQs": "طلبات العميل",
  "Customer email": "بريد العميل",
  "Customer identified": "تم تحديد العميل",
  "Customer mobile": "جوال العميل",
  "Customer name": "اسم العميل",
  "Date": "التاريخ",
  "Default": "افتراضي",
  "Default quotation margin %": "نسبة هامش عرض السعر الافتراضية %",
  "Default signature": "التوقيع الافتراضي",
  "Delete": "حذف",
  "Delete all": "حذف الكل",
  "Delete all RFQs?": "حذف جميع طلبات الأسعار؟",
  "Delete all WhatsApp messages?": "حذف جميع رسائل واتساب؟",
  "Delete all emails?": "حذف جميع رسائل البريد؟",
  "Delete entire conversation": "حذف المحادثة بالكامل",
  "Delete entire conversation?": "حذف المحادثة بالكامل؟",
  "Delete message": "حذف الرسالة",
  "Delete reply": "حذف الرد",
  "Delete signature “{{n}}”?": "حذف التوقيع “{{n}}”؟",
  "Delete this message?": "حذف هذه الرسالة؟",
  "Delete this reply?": "حذف هذا الرد؟",
  "Delete {{code}}?": "حذف {{code}}؟",
  "Delete {{name}}?": "حذف {{name}}؟",
  "Deleted {{code}}": "تم حذف {{code}}",
  "Deleted {{n}} RFQs": "تم حذف {{n}} طلب عرض سعر",
  "Deleted {{n}} messages": "تم حذف {{n}} رسالة",
  "Details": "التفاصيل",
  "Direction": "الاتجاه",
  "Discard": "تجاهل التغييرات",
  "Disconnect": "فصل",
  "Disconnect the bot WhatsApp number?": "فصل رقم واتساب البوت؟",
  "Disconnect {{e}}?": "فصل {{e}}؟",
  "Disconnected": "تم الفصل",
  "Dismiss": "إخفاء",
  "Document": "المستند",
  "Domain": "النطاق",
  "Done": "تم",
  "Drop files here or click to browse": "أفلت الملفات هنا أو انقر للاستعراض",
  "Edit": "تعديل",
  "Edit RFQ": "تعديل طلب عرض السعر",
  "Edit items": "تعديل البنود",
  "Edit supplier": "تعديل المورد",
  "Edit the RFQ to add items or extract them with AI.": "عدّل طلب عرض السعر لإضافة البنود أو استخرجها بالذكاء الاصطناعي.",
  "Email": "البريد الإلكتروني",
  "Email body": "نص الرسالة",
  "Email conversation": "محادثة البريد",
  "Email crawl started for {{n}} supplier(s)…": "بدأ البحث عن البريد لـ {{n}} مورد…",
  "Email notifications": "إشعارات البريد",
  "Email sent to {{to}}": "تم إرسال البريد إلى {{to}}",
  "Email signature": "توقيع البريد",
  "Email signatures": "تواقيع البريد",
  "Email sources": "مصادر البريد",
  "Emails": "البريد الإلكتروني",
  "Enable AI RFQ bot": "تفعيل بوت طلبات الأسعار الذكي",
  "Enable RFQ module": "تفعيل وحدة طلبات الأسعار",
  "Enter a key first.": "أدخل المفتاح أولًا.",
  "Enter a valid email address": "أدخل بريدًا إلكترونيًا صحيحًا",
  "Enter a valid recipient email address": "أدخل بريد مستلم صحيحًا",
  "Enter an API key and a keyword.": "أدخل مفتاح API وكلمة بحث.",
  "Enter at least one unit price.": "أدخل سعر وحدة واحدًا على الأقل.",
  "Enter prices manually": "إدخال الأسعار يدويًا",
  "Enter text or choose a file.": "أدخل نصًا أو اختر ملفًا.",
  "Enter the enquiry text first.": "أدخل نص الاستفسار أولًا.",
  "Enter the full international number (e.g. 966501234567)": "أدخل الرقم الدولي كاملًا (مثل 966501234567)",
  "Enter the supplier name or phone.": "أدخل اسم المورد أو رقمه.",
  "Every WhatsApp message in this store’s procurement inbox will be permanently deleted.": "سيتم حذف جميع رسائل واتساب في صندوق مشتريات هذا الفرع نهائيًا.",
  "Every email in this store’s procurement inbox will be permanently deleted.": "سيتم حذف جميع رسائل البريد في صندوق مشتريات هذا الفرع نهائيًا.",
  "Extra files (optional)": "ملفات إضافية (اختياري)",
  "Extract": "استخراج",
  "Extract RFQ with AI": "استخراج طلب عرض السعر بالذكاء الاصطناعي",
  "Extract from files": "استخراج من الملفات",
  "Extract from text": "استخراج من النص",
  "Extract prices": "استخراج الأسعار",
  "Extract supplier quotation": "استخراج عرض سعر المورد",
  "Extract with AI": "استخراج بالذكاء الاصطناعي",
  "Extracted prices": "الأسعار المستخرجة",
  "Extracted products": "المنتجات المستخرجة",
  "Extracted text": "النص المستخرج",
  "Extracted {{n}} products": "تم استخراج {{n}} منتج",
  "Extracting… reasoning models can take 1–3 minutes.": "جارٍ الاستخراج… قد تستغرق نماذج الاستدلال من دقيقة إلى 3 دقائق.",
  "Extraction timed out after 5 minutes.": "انتهت مهلة الاستخراج بعد 5 دقائق.",
  "Failed": "فشل",
  "Fetch suppliers": "جلب الموردين",
  "Fetch suppliers from Google Maps": "جلب الموردين من خرائط جوجل",
  "Fewer matches triggers a warning (default 2).": "يظهر تحذير عند وجود تطابقات أقل (الافتراضي 2).",
  "Files shown below the products on the RFQ": "ملفات تظهر أسفل المنتجات في طلب عرض السعر",
  "Files to extract from": "ملفات للاستخراج منها",
  "Fill in: {{f}}": "أكمل: {{f}}",
  "Fill markets": "تعبئة الأسواق",
  "Fills the contact placeholder in the template; blank uses the bot number.": "يملأ خانة جهة الاتصال في القالب؛ إن تُرك فارغًا يُستخدم رقم البوت.",
  "Filter suppliers": "تصفية الموردين",
  "Filter suppliers…": "تصفية الموردين…",
  "Find more suppliers for this RFQ’s categories in your purchase markets.": "ابحث عن مزيد من الموردين لفئات هذا الطلب في أسواق الشراء.",
  "First-contact message sent to new suppliers.": "رسالة التواصل الأولى المرسلة للموردين الجدد.",
  "Forward": "إعادة توجيه",
  "Forward email": "إعادة توجيه البريد",
  "Forwarded": "تم الإرسال",
  "Forwarded to": "أُرسل إلى",
  "Found {{n}} suppliers ({{db}} saved, {{maps}} from Maps)": "تم العثور على {{n}} مورد ({{db}} محفوظ، {{maps}} من الخرائط)",
  "Free-text replies only work within 24 h of the contact’s last message.": "الردود النصية الحرة تعمل فقط خلال 24 ساعة من آخر رسالة لجهة الاتصال.",
  "From": "من",
  "From address": "عنوان المرسل",
  "From message": "من الرسالة",
  "From name": "اسم المرسل",
  "General instructions": "تعليمات عامة",
  "Get a key": "احصل على مفتاح",
  "Google": "جوجل",
  "Google Maps": "خرائط جوجل",
  "Google Maps API key": "مفتاح API لخرائط جوجل",
  "Header": "الترويسة",
  "Header file": "ملف الترويسة",
  "Hide": "إخفاء",
  "Hide details": "إخفاء التفاصيل",
  "ID": "المعرّف",
  "IMAP / SMTP": "IMAP / SMTP",
  "IMAP connection OK": "اتصال IMAP يعمل",
  "IMAP host": "خادم IMAP",
  "IMAP password": "كلمة مرور IMAP",
  "IMAP port": "منفذ IMAP",
  "IMAP test failed": "فشل اختبار IMAP",
  "IMAP username": "اسم مستخدم IMAP",
  "Identified {{n}} senders": "تم التعرف على {{n}} مرسل",
  "Identify senders": "التعرف على المرسلين",
  "Ignored": "متجاهل",
  "Image": "صورة",
  "In WhatsApp → Configuration, set the callback URL and verify token, then subscribe to the “messages” field.": "في WhatsApp ← Configuration، عيّن رابط الاستدعاء ورمز التحقق ثم اشترك في حقل “messages”.",
  "Inactive": "غير نشط",
  "Incoming": "وارد",
  "Incoming & outgoing mail": "البريد الوارد والصادر",
  "Incoming email rules": "قواعد البريد الوارد",
  "Input received": "تم استلام المدخلات",
  "International format without +, e.g. 966501234567": "بالصيغة الدولية بدون +، مثل 966501234567",
  "Invoice share template": "قالب مشاركة الفاتورة",
  "Items": "البنود",
  "Items requested": "البنود المطلوبة",
  "Key rejected": "تم رفض المفتاح",
  "Key saved": "المفتاح محفوظ",
  "Key works": "المفتاح يعمل",
  "Keywords": "الكلمات المفتاحية",
  "Keywords matched in subject/body. Leave empty to accept all emails.": "كلمات تُطابق في الموضوع/النص. اتركها فارغة لقبول جميع الرسائل.",
  "Label as quotation": "تمييز كعرض سعر",
  "Labelled as supplier quotation": "تم التمييز كعرض سعر مورد",
  "Labelled as supplier quotation — matched to {{c}}": "تم التمييز كعرض سعر مورد — مطابق لـ {{c}}",
  "Link new items to the product catalog on save (creates missing products)": "ربط البنود الجديدة بكتالوج المنتجات عند الحفظ (ينشئ المنتجات غير الموجودة)",
  "Link {{n}} to catalog": "ربط {{n}} بالكتالوج",
  "Linked": "مرتبط",
  "Linked to catalog": "مرتبط بالكتالوج",
  "Loading send preview…": "جارٍ تحميل معاينة الإرسال…",
  "Manager WhatsApp numbers": "أرقام واتساب المدراء",
  "Margin %": "الهامش %",
  "Market": "السوق",
  "Market is required — choose where this supplier sells": "السوق مطلوب — اختر مكان بيع هذا المورد",
  "Markets filled: {{u}} updated, {{s}} skipped, {{f}} failed": "تعبئة الأسواق: {{u}} محدث، {{s}} متخطى، {{f}} فشل",
  "Matched": "مطابق",
  "Max per category": "الحد الأقصى لكل فئة",
  "Message": "الرسالة",
  "Message deleted": "تم حذف الرسالة",
  "Messages": "الرسائل",
  "Meta webhook": "Webhook ميتا",
  "Min per category": "الحد الأدنى لكل فئة",
  "Minimum suppliers per RFQ": "الحد الأدنى للموردين لكل طلب",
  "Missing": "مفقود",
  "Mobile": "الجوال",
  "Model": "النموذج",
  "Model used": "النموذج المستخدم",
  "Name": "الاسم",
  "Name / description": "الاسم / الوصف",
  "Name is required": "الاسم مطلوب",
  "New": "جديد",
  "New RFQ": "طلب عرض سعر جديد",
  "New RFQ supplier": "مورد طلبات أسعار جديد",
  "New email": "بريد جديد",
  "New email received": "وصل بريد جديد",
  "No API key is saved for this provider. Add it under Procurement settings → AI models, or extraction will fail.": "لا يوجد مفتاح API محفوظ لهذا المزود. أضفه من إعدادات المشتريات ← نماذج الذكاء الاصطناعي وإلا سيفشل الاستخراج.",
  "No Google Maps match found": "لم يتم العثور على تطابق في خرائط جوجل",
  "No RFQ": "بدون طلب",
  "No RFQs yet": "لا توجد طلبات أسعار بعد",
  "No WABA template is configured for RFQs.": "لم يتم إعداد قالب WABA لطلبات الأسعار.",
  "No activity yet": "لا يوجد نشاط بعد",
  "No conversations": "لا توجد محادثات",
  "No customer with this number.": "لا يوجد عميل بهذا الرقم.",
  "No email accounts connected": "لا توجد حسابات بريد مرتبطة",
  "No email addresses on this RFQ yet.": "لا توجد عناوين بريد في هذا الطلب بعد.",
  "No items captured": "لم يتم تسجيل بنود",
  "No key": "لا يوجد مفتاح",
  "No messages": "لا توجد رسائل",
  "No messages yet": "لا توجد رسائل بعد",
  "No new WhatsApp messages.": "لا توجد رسائل واتساب جديدة.",
  "No new emails.": "لا توجد رسائل بريد جديدة.",
  "No new messages": "لا توجد رسائل جديدة",
  "No phone numbers on this RFQ yet.": "لا توجد أرقام هواتف في هذا الطلب بعد.",
  "No purchase markets configured — add one below.": "لم يتم إعداد أسواق شراء — أضف سوقًا أدناه.",
  "No replies yet": "لا توجد ردود بعد",
  "No senders to check": "لا يوجد مرسلون للتحقق",
  "No signatures yet.": "لا توجد تواقيع بعد.",
  "No supplier quotations yet": "لا توجد عروض أسعار من الموردين بعد",
  "No suppliers found": "لم يتم العثور على موردين",
  "No suppliers matched yet": "لا يوجد موردون مطابقون بعد",
  "No suppliers yet": "لا يوجد موردون بعد",
  "No template selected yet.": "لم يتم اختيار قالب بعد.",
  "None": "لا شيء",
  "None of the extracted prices could be matched to this RFQ’s items.": "تعذرت مطابقة أي من الأسعار المستخرجة مع بنود هذا الطلب.",
  "Not a quotation": "ليس عرض سعر",
  "Not a saved supplier.": "ليس موردًا محفوظًا.",
  "Not categorised yet": "لم يُصنّف بعد",
  "Not clearly a quotation": "ليس عرض سعر بوضوح",
  "Not connected": "غير متصل",
  "Not linked": "غير مرتبط",
  "Not sent": "لم يُرسل",
  "Not sent to any supplier yet": "لم يُرسل إلى أي مورد بعد",
  "Not set": "غير محدد",
  "Notes": "ملاحظات",
  "Number": "الرقم",
  "Only administrators and managers can change store settings.": "يمكن للمسؤولين والمدراء فقط تغيير إعدادات الفرع.",
  "Only these numbers can create RFQs. Empty = everyone.": "هذه الأرقام فقط يمكنها إنشاء طلبات الأسعار. فارغ = الجميع.",
  "Open": "فتح",
  "Open AI models settings": "فتح إعدادات نماذج الذكاء الاصطناعي",
  "Open Google settings": "فتح إعدادات جوجل",
  "Open RFQ": "فتح طلب عرض السعر",
  "Open conversation": "فتح المحادثة",
  "Open email settings": "فتح إعدادات البريد",
  "Or attach product files": "أو أرفق ملفات المنتجات",
  "Other": "أخرى",
  "Outgoing": "صادر",
  "Outgoing email": "البريد الصادر",
  "Overview": "نظرة عامة",
  "PDF": "PDF",
  "Part No.": "رقم القطعة",
  "Password": "كلمة المرور",
  "Passwords are write-only; leave blank to keep the saved one.": "كلمات المرور للكتابة فقط؛ اتركها فارغة للإبقاء على المحفوظة.",
  "Paste the supplier’s reply text.": "الصق نص رد المورد.",
  "Pending": "قيد الانتظار",
  "Permanently delete {{code}}? This will also unlink it from any connected email or WhatsApp message.": "حذف {{code}} نهائيًا؟ سيتم أيضًا فك ارتباطه بأي رسالة بريد أو واتساب مرتبطة.",
  "Phone": "الهاتف",
  "Phone Number ID": "معرّف رقم الهاتف",
  "Phone Number ID and Access Token are required.": "معرّف رقم الهاتف ورمز الوصول مطلوبان.",
  "Pick a contact on the left or start a new conversation.": "اختر جهة اتصال من القائمة أو ابدأ محادثة جديدة.",
  "Pin": "تثبيت",
  "Places found": "الأماكن التي تم العثور عليها",
  "Point your provider’s inbound webhook to:": "وجّه Webhook الوارد لدى المزود إلى:",
  "Populate RFQ suppliers from vendors": "تعبئة موردي طلبات الأسعار من الموردين",
  "Populate suppliers": "تعبئة الموردين",
  "Populating suppliers…": "جارٍ تعبئة الموردين…",
  "Port": "المنفذ",
  "Pre-select these markets when sending": "تحديد هذه الأسواق مسبقًا عند الإرسال",
  "Press Enter after each number.": "اضغط Enter بعد كل رقم.",
  "Price comparison": "مقارنة الأسعار",
  "Prices": "الأسعار",
  "Prices appear here when suppliers reply with a quotation, or add one from a file.": "تظهر الأسعار هنا عندما يرد الموردون بعرض سعر، أو أضف عرضًا من ملف.",
  "Prices extracted": "تم استخراج الأسعار",
  "Prices updated": "تم تحديث الأسعار",
  "Print": "طباعة",
  "Processed": "تمت المعالجة",
  "Processing": "قيد المعالجة",
  "Processing complete.": "اكتملت المعالجة.",
  "Processing failed.": "فشلت المعالجة.",
  "Procurement mailbox — customer enquiries and supplier quotations": "بريد المشتريات — استفسارات العملاء وعروض الموردين",
  "Procurement settings": "إعدادات المشتريات",
  "Procurement settings saved": "تم حفظ إعدادات المشتريات",
  "Product": "المنتج",
  "Product files replace the products table on the RFQ document.": "ملفات المنتجات تحل محل جدول المنتجات في مستند الطلب.",
  "Product name": "اسم المنتج",
  "Products": "المنتجات",
  "Products identified": "تم تحديد المنتجات",
  "Products required": "المنتجات المطلوبة",
  "Provider": "المزود",
  "Publish your Meta app (Live mode).": "انشر تطبيق ميتا (الوضع المباشر).",
  "Purchase bills": "فواتير المشتريات",
  "Purchase bills tracking": "تتبع فواتير المشتريات",
  "Purchase market": "سوق الشراء",
  "Purchase markets": "أسواق الشراء",
  "Qty": "الكمية",
  "Quotation": "عرض سعر",
  "Quotation detected": "تم اكتشاف عرض سعر",
  "Quotation extraction": "استخراج عروض الأسعار",
  "Quotation label removed": "تمت إزالة تمييز عرض السعر",
  "Quotations": "عروض الأسعار",
  "RFQ": "طلب عرض سعر",
  "RFQ #": "رقم الطلب",
  "RFQ created": "تم إنشاء الطلب",
  "RFQ created: {{code}}": "تم إنشاء طلب عرض السعر: {{code}}",
  "RFQ document title": "عنوان مستند الطلب",
  "RFQ filter": "تصفية الطلبات",
  "RFQ ignored.": "تم تجاهل الطلب.",
  "RFQ inbox": "صندوق طلبات الأسعار",
  "RFQ intro": "مقدمة الطلب",
  "RFQ message contact number": "رقم التواصل في رسالة الطلب",
  "RFQ module & quotations": "وحدة الطلبات وعروض الأسعار",
  "RFQ parsing": "تحليل الطلبات",
  "RFQ rules": "قواعد الطلبات",
  "RFQ sections": "أقسام الطلب",
  "RFQ suppliers": "موردو طلبات الأسعار",
  "RFQ to supplier template": "قالب طلب عرض السعر للمورد",
  "RFQs": "طلبات الأسعار",
  "RFQs arrive automatically from the bot WhatsApp number and connected email accounts, or create one manually.": "تصل طلبات الأسعار تلقائيًا من رقم واتساب البوت وحسابات البريد المرتبطة، أو أنشئ طلبًا يدويًا.",
  "RFQs will no longer arrive by WhatsApp and sending to suppliers stops working.": "لن تصل طلبات الأسعار عبر واتساب وسيتوقف الإرسال إلى الموردين.",
  "Rating": "التقييم",
  "Rating must be between 0 and 5": "يجب أن يكون التقييم بين 0 و5",
  "Raw output": "المخرجات الخام",
  "Re-process": "إعادة المعالجة",
  "Re-processing {{code}}…": "جارٍ إعادة معالجة {{code}}…",
  "Ready to send": "جاهز للإرسال",
  "Ready to send to suppliers": "جاهز للإرسال إلى الموردين",
  "Ready to send to suppliers!": "جاهز للإرسال إلى الموردين!",
  "Received": "مستلم",
  "Recipients": "المستلمون",
  "Record voice note": "تسجيل رسالة صوتية",
  "Refetch from Google Maps": "إعادة الجلب من خرائط جوجل",
  "Refresh": "تحديث",
  "Refresh templates": "تحديث القوالب",
  "Region": "المنطقة",
  "Remove": "إزالة",
  "Remove duplicates": "إزالة المكرر",
  "Remove quotation label": "إزالة تمييز عرض السعر",
  "Remove row": "حذف السطر",
  "Removed {{n}} duplicates": "تمت إزالة {{n}} مكرر",
  "Replies": "الردود",
  "Reply": "رد",
  "Reply added — AI is extracting prices": "تمت إضافة الرد — الذكاء الاصطناعي يستخرج الأسعار",
  "Reply deleted": "تم حذف الرد",
  "Reply sent": "تم إرسال الرد",
  "Reply text": "نص الرد",
  "Reply to latest": "الرد على الأحدث",
  "Requests for quotation from WhatsApp, email and manual entry": "طلبات عروض الأسعار من واتساب والبريد والإدخال اليدوي",
  "Retail price": "سعر البيع",
  "Retry download": "إعادة التنزيل",
  "Review prices": "مراجعة الأسعار",
  "Run AI categorisation, add suppliers manually, or fetch them from Google Maps.": "شغّل التصنيف بالذكاء الاصطناعي أو أضف الموردين يدويًا أو اجلبهم من خرائط جوجل.",
  "Run test": "تشغيل الاختبار",
  "SMTP host": "خادم SMTP",
  "SMTP password": "كلمة مرور SMTP",
  "SMTP password (optional)": "كلمة مرور SMTP (اختياري)",
  "SMTP port": "منفذ SMTP",
  "SMTP username": "اسم مستخدم SMTP",
  "SMTP username (optional)": "اسم مستخدم SMTP (اختياري)",
  "Sample enquiry text": "نص استفسار تجريبي",
  "Sample files": "ملفات تجريبية",
  "Save": "حفظ",
  "Save ID": "حفظ المعرّف",
  "Save changes": "حفظ التغييرات",
  "Saved {{code}}": "تم حفظ {{code}}",
  "Search": "بحث",
  "Search by email address…": "ابحث بالبريد الإلكتروني…",
  "Search code, customer, phone, category…": "ابحث بالرقم أو العميل أو الهاتف أو الفئة…",
  "Search conversations": "البحث في المحادثات",
  "Search customers…": "ابحث عن العملاء…",
  "Search from, subject or body…": "ابحث في المرسل أو الموضوع أو النص…",
  "Search messages": "البحث في الرسائل",
  "Search name or number…": "ابحث بالاسم أو الرقم…",
  "Search name, phone, address, category…": "ابحث بالاسم أو الهاتف أو العنوان أو الفئة…",
  "Search products…": "ابحث عن المنتجات…",
  "Search sender or text…": "ابحث بالمرسل أو النص…",
  "Search suppliers by name or phone, or type a full number to add it.": "ابحث عن الموردين بالاسم أو الرقم، أو اكتب رقمًا كاملًا لإضافته.",
  "Search suppliers…": "ابحث عن الموردين…",
  "Searching for matching suppliers…": "جارٍ البحث عن موردين مطابقين…",
  "Secret key": "المفتاح السري",
  "Select": "تحديد",
  "Select RFQ": "اختر طلب عرض السعر",
  "Select a conversation": "اختر محادثة",
  "Select a supplier price for at least one catalog-linked product.": "اختر سعر مورد لمنتج واحد مرتبط بالكتالوج على الأقل.",
  "Select at least one market.": "اختر سوقًا واحدًا على الأقل.",
  "Select at least one supplier.": "اختر موردًا واحدًا على الأقل.",
  "Select market": "اختر السوق",
  "Selected supplier": "المورد المختار",
  "Send": "إرسال",
  "Send a test email to": "إرسال بريد تجريبي إلى",
  "Send a test message to": "إرسال رسالة تجريبية إلى",
  "Send failed": "فشل الإرسال",
  "Send reply": "إرسال الرد",
  "Send test": "إرسال تجربة",
  "Send to": "إرسال إلى",
  "Send to suppliers": "إرسال إلى الموردين",
  "Send to {{n}} supplier(s)": "إرسال إلى {{n}} مورد",
  "Sending": "جارٍ الإرسال",
  "Sent": "مرسل",
  "Sent at": "وقت الإرسال",
  "Sent from": "أُرسل من",
  "Sent to supplier": "أُرسل إلى المورد",
  "Sent to {{n}} supplier(s)": "تم الإرسال إلى {{n}} مورد",
  "Sent via WhatsApp": "أُرسل عبر واتساب",
  "Server token": "رمز الخادم",
  "Settings": "الإعدادات",
  "Settings sections": "أقسام الإعدادات",
  "Show": "إظهار",
  "Show sent message": "عرض الرسالة المرسلة",
  "Shows the RFQ inbox and suppliers (also needs the AI RFQ bot).": "يُظهر صندوق الطلبات والموردين (يتطلب أيضًا بوت الطلبات الذكي).",
  "Signatures saved": "تم حفظ التواقيع",
  "Some attachments could not be downloaded — RFQ creation is blocked until they are available.": "تعذر تنزيل بعض المرفقات — إنشاء الطلب متوقف حتى تتوفر.",
  "Some attachments failed to download. Retry or upload them before extracting.": "فشل تنزيل بعض المرفقات. أعد المحاولة أو ارفعها قبل الاستخراج.",
  "Some files were skipped (unsupported type).": "تم تخطي بعض الملفات (نوع غير مدعوم).",
  "Source message": "الرسالة المصدر",
  "Start new conversation": "بدء محادثة جديدة",
  "Start the conversation below. New contacts must first receive an approved template (e.g. an RFQ).": "ابدأ المحادثة أدناه. يجب أن تستلم جهات الاتصال الجديدة قالبًا معتمدًا أولًا (مثل طلب عرض سعر).",
  "Starting…": "جارٍ البدء…",
  "Status": "الحالة",
  "Stop recording": "إيقاف التسجيل",
  "Subject": "الموضوع",
  "Subscribe the app to your WhatsApp Business Account.": "اشترك بالتطبيق في حساب واتساب للأعمال.",
  "Suggested: {{c}}": "مقترح: {{c}}",
  "Supplier": "المورد",
  "Supplier RFQ history": "سجل طلبات المورد",
  "Supplier RFQs": "طلبات المورد",
  "Supplier added": "تمت إضافة المورد",
  "Supplier and customer conversations on the procurement WhatsApp number": "محادثات الموردين والعملاء على رقم واتساب المشتريات",
  "Supplier deleted": "تم حذف المورد",
  "Supplier name": "اسم المورد",
  "Supplier phone": "هاتف المورد",
  "Supplier population": "تعبئة الموردين",
  "Supplier population finished": "اكتملت تعبئة الموردين",
  "Supplier quotation": "عرض سعر مورد",
  "Supplier quotation files": "ملفات عرض سعر المورد",
  "Supplier replied": "رد المورد",
  "Supplier replies": "ردود الموردين",
  "Supplier replies on WhatsApp or email are linked here automatically.": "تُربط ردود الموردين عبر واتساب أو البريد هنا تلقائيًا.",
  "Supplier saved": "تم حفظ المورد",
  "Suppliers": "الموردون",
  "Suppliers are assigned to one of these markets.": "يُعيَّن الموردون إلى أحد هذه الأسواق.",
  "Suppliers below minimum": "الموردون أقل من الحد الأدنى",
  "Suppliers contacted": "الموردون الذين تم التواصل معهم",
  "Suppliers matched": "تمت مطابقة الموردين",
  "Suppliers that receive RFQs on WhatsApp, matched by category and market": "الموردون الذين يستلمون طلبات الأسعار عبر واتساب حسب الفئة والسوق",
  "Sync now": "مزامنة الآن",
  "Sync started — new emails appear in a few seconds": "بدأت المزامنة — ستظهر الرسائل الجديدة خلال ثوانٍ",
  "Template": "القالب",
  "Template tester": "اختبار القوالب",
  "Templates are loaded from Meta once the bot number is connected and the WABA ID is saved.": "تُحمّل القوالب من ميتا بعد ربط رقم البوت وحفظ معرّف WABA.",
  "Tenant ID": "معرّف المستأجر",
  "Test": "اختبار",
  "Test IMAP": "اختبار IMAP",
  "Test email sent to {{to}}": "تم إرسال بريد تجريبي إلى {{to}}",
  "Test key": "اختبار المفتاح",
  "Test keyword": "كلمة البحث التجريبية",
  "Test message sent": "تم إرسال الرسالة التجريبية",
  "Test message sent to {{p}}": "تم إرسال رسالة تجريبية إلى {{p}}",
  "The message is removed from the procurement inbox.": "ستتم إزالة الرسالة من صندوق المشتريات.",
  "The reply from {{s}} and its prices will be removed from the comparison.": "سيتم حذف رد {{s}} وأسعاره من المقارنة.",
  "The supplier will no longer receive RFQs.": "لن يستلم المورد طلبات الأسعار بعد الآن.",
  "These replace the products table (cannot be changed after creation)": "تحل محل جدول المنتجات (لا يمكن تغييرها بعد الإنشاء)",
  "This RFQ has no item list (attachments only), so prices can’t be compared per item.": "هذا الطلب بلا قائمة بنود (مرفقات فقط)، لذا لا يمكن مقارنة الأسعار لكل بند.",
  "This RFQ uses attached product files instead of an item list.": "يستخدم هذا الطلب ملفات منتجات مرفقة بدل قائمة البنود.",
  "This permanently deletes every RFQ in this store. This cannot be undone.": "سيحذف هذا جميع طلبات الأسعار في هذا الفرع نهائيًا. لا يمكن التراجع.",
  "This template needs a header file.": "يتطلب هذا القالب ملف ترويسة.",
  "Timeline": "السجل الزمني",
  "To": "إلى",
  "Today": "اليوم",
  "Track purchase bill images & PDFs": "تتبع صور وملفات فواتير المشتريات",
  "Translate": "ترجمة",
  "Translate to Arabic": "ترجمة إلى العربية",
  "Translation failed": "فشلت الترجمة",
  "Try different filters, or check the connection in Procurement settings.": "جرّب عوامل تصفية أخرى أو تحقق من الاتصال في إعدادات المشتريات.",
  "Turns on the procurement inboxes and automatic RFQ creation from WhatsApp and email.": "يفعّل صناديق المشتريات والإنشاء التلقائي للطلبات من واتساب والبريد.",
  "Type": "النوع",
  "Type a message — Ctrl+Enter to send": "اكتب رسالة — Ctrl+Enter للإرسال",
  "Type a reply first.": "اكتب ردًا أولًا.",
  "Unit": "الوحدة",
  "Unit price": "سعر الوحدة",
  "Unpin": "إلغاء التثبيت",
  "Unread WhatsApp messages": "رسائل واتساب غير مقروءة",
  "Update product prices": "تحديث أسعار المنتجات",
  "Updated from Google Maps": "تم التحديث من خرائط جوجل",
  "Upload": "رفع",
  "Upload the customer’s enquiry (PDF, Excel, image or text) and let AI fill in the customer and items. Large files with reasoning models can take 1–3 minutes.": "ارفع استفسار العميل (PDF أو Excel أو صورة أو نص) ودع الذكاء الاصطناعي يملأ بيانات العميل والبنود. قد تستغرق الملفات الكبيرة من دقيقة إلى 3 دقائق.",
  "Use SSL": "استخدام SSL",
  "Use TLS": "استخدام TLS",
  "Use thank-you reply": "استخدام رد الشكر",
  "Use the Send tab to send this RFQ to matching suppliers.": "استخدم تبويب الإرسال لإرسال هذا الطلب إلى الموردين المطابقين.",
  "Use the mailbox’s own SMTP": "استخدام SMTP الخاص بصندوق البريد",
  "Used in price comparison when a product has no margin (default 35).": "يُستخدم في مقارنة الأسعار عندما لا يكون للمنتج هامش (الافتراضي 35).",
  "Used to find suppliers near your purchase markets (Places API).": "يُستخدم للعثور على موردين قرب أسواق الشراء (Places API).",
  "Username": "اسم المستخدم",
  "Uses the saved settings — save first.": "يستخدم الإعدادات المحفوظة — احفظ أولًا.",
  "VAT": "الضريبة",
  "Verify token": "رمز التحقق",
  "View": "العرض",
  "View RFQ": "عرض الطلب",
  "View full email": "عرض البريد كاملًا",
  "Voice recording isn’t supported in this browser.": "التسجيل الصوتي غير مدعوم في هذا المتصفح.",
  "WABA Business Account ID": "معرّف حساب WABA التجاري",
  "WABA Business Account ID saved": "تم حفظ معرّف حساب WABA",
  "Waiting approval": "بانتظار الموافقة",
  "Waiting for authorisation…": "بانتظار التفويض…",
  "Waiting for connection…": "بانتظار الاتصال…",
  "Waiting replies": "بانتظار الردود",
  "Website": "الموقع الإلكتروني",
  "WhatsApp": "واتساب",
  "WhatsApp bot, email accounts, AI models and RFQ rules for": "بوت واتساب وحسابات البريد ونماذج الذكاء الاصطناعي وقواعد الطلبات لـ",
  "WhatsApp chat": "محادثة واتساب",
  "WhatsApp messages": "رسائل واتساب",
  "WhatsApp messages from the manager numbers below are collected as purchase bills.": "تُجمع رسائل واتساب من أرقام المدراء أدناه كفواتير مشتريات.",
  "WhatsApp messages to the bot number appear here.": "تظهر هنا رسائل واتساب المرسلة إلى رقم البوت.",
  "WhatsApp notifications": "إشعارات واتساب",
  "WhatsApp number": "رقم واتساب",
  "WhatsApp number 2": "رقم واتساب 2",
  "WhatsApp number is required": "رقم واتساب مطلوب",
  "WhatsApp preview": "معاينة واتساب",
  "WhatsApp templates": "قوالب واتساب",
  "With attachments": "مع مرفقات",
  "Write a message": "اكتب رسالة",
  "Yesterday": "أمس",
  "You don’t have permission to do this.": "ليست لديك صلاحية للقيام بذلك.",
  "You sent": "أرسلت",
  "added": "مضاف",
  "customer": "عميل",
  "document": "مستند",
  "done": "مكتمل",
  "download failed": "فشل التنزيل",
  "e.g. 971501234567": "مثال 971501234567",
  "e.g. Brake parts": "مثال: قطع الفرامل",
  "e.g. RFQ, quotation": "مثال: طلب عرض سعر، عرض سعر",
  "e.g. Riyadh": "مثال: الرياض",
  "e.g. auto spare parts": "مثال: قطع غيار سيارات",
  "email": "بريد إلكتروني",
  "excl. VAT": "غير شامل الضريبة",
  "failed": "فشل",
  "files": "ملفات",
  "free-text messages only work within 24 h of the contact’s last message; use the RFQ template otherwise.": "الرسائل النصية الحرة تعمل فقط خلال 24 ساعة من آخر رسالة لجهة الاتصال؛ استخدم قالب الطلب في غير ذلك.",
  "from": "من",
  "image": "صورة",
  "incl. VAT": "شامل الضريبة",
  "is attached as the header document": "مرفق كمستند الترويسة",
  "last checked": "آخر فحص",
  "lowest": "الأقل",
  "manual": "يدوي",
  "media message": "رسالة وسائط",
  "message text": "نص الرسالة",
  "mixed": "مختلط",
  "model": "النموذج",
  "pending": "قيد الانتظار",
  "provider": "المزود",
  "supplier": "مورد",
  "text": "نص",
  "then authorise in the pop-up window.": "ثم فوّض من النافذة المنبثقة.",
  "used": "مستخدم",
  "whatsapp": "واتساب",
  "{{n}} accounts": "{{n}} حسابات",
  "{{n}} attachments": "{{n}} مرفقات",
  "{{n}} emails": "{{n}} رسائل",
  "{{n}} extra files": "{{n}} ملفات إضافية",
  "{{n}} messages": "{{n}} رسالة",
  "{{n}} new messages": "{{n}} رسائل جديدة",
  "{{n}} new messages for {{code}}": "{{n}} رسائل جديدة للطلب {{code}}",
  "{{n}} prices": "{{n}} أسعار",
  "{{n}} products could not be linked to the catalog": "تعذر ربط {{n}} منتج بالكتالوج",
  "{{n}} quotes": "{{n}} عروض",
  "{{n}} replies": "{{n}} ردود",
  "{{n}} unread": "{{n}} غير مقروءة",
  "{{n}} unsaved changes": "{{n}} تغييرات غير محفوظة",
  "{{u}} updated, {{s}} skipped": "{{u}} محدث، {{s}} متخطى",
};
