// Arabic strings for quotations, delivery notes and quotation sales returns (keys = English source text).
export const ar: Record<string, string> = {
  // Quotations
  'Quotations': 'عروض الأسعار', 'Quotation': 'عرض سعر', 'New quotation': 'عرض سعر جديد', 'Quotation #': 'رقم عرض السعر',
  'Quotations and sales recorded as quotation invoices': 'عروض الأسعار والمبيعات المسجلة كفواتير عروض أسعار', 'Price offers sent to customers': 'عروض الأسعار المرسلة للعملاء',
  'Search quotation # or sales invoice #…': 'ابحث برقم عرض السعر أو رقم فاتورة المبيعات…', 'New sales (quotation invoice)': 'مبيعات جديدة (فاتورة عرض سعر)',
  'All': 'الكل', 'Not invoiced': 'غير مفوتر', 'Invoiced': 'مفوتر', 'Unpaid sales': 'مبيعات غير مدفوعة', 'Sales': 'المبيعات', 'Sales (invoice)': 'مبيعات (فاتورة)',
  'Profit': 'الربح', 'Profit %': 'نسبة الربح', 'Loss': 'الخسارة', 'Paid sales': 'المبيعات المدفوعة', 'Sales net profit': 'صافي ربح المبيعات', 'Credit (unpaid)': 'آجل (غير مدفوع)', 'VAT collected': 'الضريبة المحصلة',
  'Type': 'النوع', 'Status': 'الحالة', 'Expired': 'منتهي الصلاحية', 'Validity (days)': 'الصلاحية (أيام)', 'Valid until': 'صالح حتى', 'Delivery (days)': 'التسليم (أيام)', 'Delivery from': 'التسليم من',
  'RFQ': 'طلب عرض سعر', 'Validity': 'الصلاحية', 'Delivery': 'التسليم', 'days': 'أيام', 'Terms': 'الشروط', 'Delivered by': 'سلّمه',
  'Created': 'تم الإنشاء', 'Delivered': 'تم التسليم', 'Pending': 'قيد الانتظار', 'Accepted': 'مقبول', 'Rejected': 'مرفوض', 'Cancelled': 'ملغى', 'Received': 'مستلم', 'Sent': 'مرسل',
  'Partially paid': 'مدفوع جزئياً', 'Paid': 'مدفوع', 'Unpaid': 'غير مدفوع', 'Partially refunded': 'مسترد جزئياً', 'Refunded': 'مسترد',
  'Create invoice': 'إنشاء فاتورة', 'Receive payment': 'استلام دفعة', 'Return': 'مرتجع', 'Create return': 'إنشاء مرتجع', 'Returns': 'المرتجعات', 'Invoice': 'فاتورة',
  'Sales invoices': 'فواتير المبيعات', 'Invoices created from this quotation': 'الفواتير المنشأة من عرض السعر هذا', 'Not invoiced yet.': 'لم تتم الفوترة بعد.',
  'Unlink {{code}}?': 'إلغاء ربط {{code}}؟', 'The sales invoice stays; it just won’t be linked to this quotation any more.': 'تبقى فاتورة المبيعات، لكنها لن تكون مرتبطة بعرض السعر هذا بعد الآن.',
  'Unlink': 'إلغاء الربط', '{{code}} unlinked': 'تم إلغاء ربط {{code}}', 'Delete {{code}}?': 'حذف {{code}}؟', '{{code}} deleted': 'تم حذف {{code}}',
  'The quotation will be removed from lists. This can’t be undone here.': 'سيتم إزالة عرض السعر من القوائم. لا يمكن التراجع عن ذلك هنا.',
  'Reported': 'تم الإبلاغ', 'Not reported': 'لم يتم الإبلاغ', 'Yes': 'نعم', 'No': 'لا', 'Total incl. VAT': 'الإجمالي شامل الضريبة', 'Balance due': 'المبلغ المستحق', 'Net profit': 'صافي الربح',
  'Validity days are required': 'أيام الصلاحية مطلوبة', 'Delivery days are required': 'أيام التسليم مطلوبة',
  'Validity days should be a whole number greater than 0': 'يجب أن تكون أيام الصلاحية عدداً صحيحاً أكبر من 0', 'Delivery days should be a whole number greater than 0': 'يجب أن تكون أيام التسليم عدداً صحيحاً أكبر من 0',
  'Customer': 'العميل', 'Payment status': 'حالة الدفع', 'Payment method': 'طريقة الدفع', 'Payment': 'الدفع', 'ZATCA': 'زاتكا', 'Amount': 'المبلغ', 'Balance': 'الرصيد', 'Total': 'الإجمالي',
  'Download PDF': 'تنزيل PDF', 'WhatsApp': 'واتساب',

  // Delivery notes
  'Delivery notes': 'إشعارات التسليم', 'Delivery note': 'إشعار تسليم', 'Delivery note #': 'رقم إشعار التسليم', 'New delivery note': 'إشعار تسليم جديد',
  'Goods handed over to customers, before or without an invoice': 'بضائع سُلّمت للعملاء قبل الفوترة أو بدونها', 'Search delivery note # or sales invoice #…': 'ابحث برقم إشعار التسليم أو رقم فاتورة المبيعات…',
  'Reminder due': 'حان التذكير', 'Sales invoice': 'فاتورة المبيعات', 'Sales invoice #': 'رقم فاتورة المبيعات', 'Reminder': 'التذكير', 'Reminder (notify at)': 'التذكير (موعد التنبيه)',
  'Reminds you to invoice this delivery.': 'يذكّرك بفوترة هذا التسليم.', 'Items': 'الأصناف', 'qty': 'كمية', 'e.g. >=1000': 'مثال: >=1000', 'Discount': 'الخصم', 'Shipping & handling': 'الشحن والمناولة', 'VAT': 'الضريبة',

  // Quotation sales returns
  'Quotation sales returns': 'مرتجعات مبيعات عروض الأسعار', 'New quotation sales return': 'مرتجع مبيعات عرض سعر جديد', 'Returns against sales recorded as quotation invoices': 'مرتجعات المبيعات المسجلة كفواتير عروض أسعار',
  'Search return # or quotation #…': 'ابحث برقم المرتجع أو رقم عرض السعر…', 'New return': 'مرتجع جديد', 'All returns': 'كل المرتجعات', 'Refund due': 'استرداد مستحق',
  'Return #': 'رقم المرتجع', 'Sales returns': 'مرتجعات المبيعات', 'Cash': 'نقداً', 'Bank': 'البنك', 'VAT returned': 'الضريبة المستردة', 'Net loss': 'صافي الخسارة',
  'Debit card': 'بطاقة مدى', 'Credit card': 'بطاقة ائتمان', 'Bank card': 'بطاقة بنكية', 'Bank transfer': 'تحويل بنكي', 'Bank cheque': 'شيك بنكي', 'Customer account': 'حساب العميل', 'Quotation sales': 'مبيعات عرض السعر',
  'Return quantity': 'كمية المرتجع', 'max': 'الحد الأقصى', 'Items to return': 'الأصناف المرتجعة', 'Select all': 'تحديد الكل', 'Item': 'الصنف', 'Qty': 'الكمية', 'Unit price': 'سعر الوحدة',
  'ex VAT': 'بدون ضريبة', 'incl. VAT': 'شامل الضريبة', 'Disc.': 'خصم', 'per unit': 'للوحدة', 'Unit discount': 'خصم الوحدة', 'No items on this quotation': 'لا توجد أصناف في عرض السعر هذا',
  'Already returned in full': 'تم إرجاعه بالكامل', 'Already returned in full.': 'تم إرجاعه بالكامل.', 'More than what is left to return.': 'أكثر من الكمية المتبقية للإرجاع.',
  'Select at least one item to return.': 'اختر صنفاً واحداً على الأقل للإرجاع.', 'Quantity must be greater than zero.': 'يجب أن تكون الكمية أكبر من صفر.', 'Discount can’t exceed the unit price.': 'لا يمكن أن يتجاوز الخصم سعر الوحدة.',
  'The return total can’t exceed the original invoice total.': 'لا يمكن أن يتجاوز إجمالي المرتجع إجمالي الفاتورة الأصلية.', 'Cash discount must be less than the total.': 'يجب أن يكون الخصم النقدي أقل من الإجمالي.',
  'Refunds can’t exceed the return total.': 'لا يمكن أن تتجاوز المبالغ المستردة إجمالي المرتجع.', 'Refunds can’t exceed what the customer paid on the invoice.': 'لا يمكن أن تتجاوز المبالغ المستردة ما دفعه العميل على الفاتورة.',
  'Date is required': 'التاريخ مطلوب',
  'Which sale is being returned?': 'ما هي عملية البيع المرتجعة؟', 'Returns are recorded against a quotation invoice (sales in quotation).': 'تُسجل المرتجعات مقابل فاتورة عرض سعر (المبيعات ضمن عروض الأسعار).',
  'Quotation invoice': 'فاتورة عرض السعر', 'Search quotation #…': 'ابحث برقم عرض السعر…', 'Please fix the highlighted fields.': 'يرجى تصحيح الحقول المحددة.', '{{code}} created': 'تم إنشاء {{code}}',
  'Against': 'مقابل', 'Draft': 'مسودة', 'Unsaved': 'غير محفوظ', 'Summary': 'الملخص', 'Refund': 'الاسترداد', 'Refundable (paid on the invoice)': 'قابل للاسترداد (المدفوع على الفاتورة)',
  'The invoice was not paid, so nothing is refunded — the return reduces the customer’s balance.': 'لم تُدفع الفاتورة، لذا لا يوجد استرداد — المرتجع يخفض رصيد العميل.',
  'Couldn’t save.': 'تعذر الحفظ.', 'Details': 'التفاصيل',
  'Only sales recorded as quotation invoices can be returned. Convert the quotation to a sales invoice and return that instead.': 'يمكن إرجاع المبيعات المسجلة كفواتير عروض أسعار فقط. حوّل عرض السعر إلى فاتورة مبيعات ثم أرجعها.',
  'Delete this refund of {{a}}?': 'حذف هذا الاسترداد بمبلغ {{a}}؟', 'Refund deleted': 'تم حذف الاسترداد', 'Refunds': 'المبالغ المستردة', 'No refunds recorded.': 'لا توجد مبالغ مستردة.',
  'Delete refund': 'حذف الاسترداد', 'Return total': 'إجمالي المرتجع', 'Record refund': 'تسجيل استرداد',
};
