// Arabic strings for the workshop & HR module, keyed by the English text (legacy key names reused).
export const ar: Record<string, string> = {
  // common
  'Workshop': 'الورشة', 'Workshop dashboard': 'لوحة الورشة', 'Dashboard': 'لوحة التحكم', 'Actions': 'الإجراءات', 'Add': 'إضافة', 'All': 'الكل', 'Amount': 'المبلغ', 'Balance': 'الرصيد',
  'Cancel': 'إلغاء', 'Clear': 'مسح', 'Code': 'الرمز', 'Create': 'إنشاء', 'Customer': 'العميل', 'Date': 'التاريخ', 'Delete': 'حذف', 'Description': 'الوصف', 'Details': 'التفاصيل',
  'Done': 'تم', 'Edit': 'تعديل', 'ID': 'المعرف', 'Method': 'الطريقة', 'Name': 'الاسم', 'New': 'جديد', 'OK': 'موافق', 'Open': 'مفتوح', 'Closed': 'مغلق', 'Optional': 'اختياري',
  'Phone': 'الهاتف', 'Refresh': 'تحديث', 'Remarks': 'ملاحظات', 'Remove': 'إزالة', 'Save': 'حفظ', 'Save changes': 'حفظ التغييرات', 'Select': 'اختيار', 'Select all': 'تحديد الكل', 'Status': 'الحالة',
  'Table': 'الجدول', 'Title': 'العنوان', 'Total': 'الإجمالي', 'VAT': 'الضريبة', 'VAT no.': 'الرقم الضريبي', 'Year': 'السنة', 'Month': 'الشهر', 'Filters': 'عوامل التصفية', 'Breakdown': 'التفاصيل',
  'Show table': 'عرض الجدول', 'Document flow': 'تسلسل المستندات', 'Invoice': 'فاتورة', 'Quotation': 'عرض سعر', 'Sales Invoice': 'فاتورة مبيعات', 'Non VAT Invoice': 'فاتورة بدون ضريبة',
  'Failed to save': 'فشل الحفظ', 'Archived': 'مؤرشف', 'Unarchived': 'تم إلغاء الأرشفة', 'Archive': 'أرشفة', 'Unarchive': 'إلغاء الأرشفة', 'Service': 'خدمة', 'in stock': 'في المخزون', 'Auto': 'تلقائي',
  '{{n}} error(s) — please fix before saving:': '{{n}} خطأ — يرجى التصحيح قبل الحفظ:', 'please fix before saving': 'يرجى التصحيح قبل الحفظ',
  'In progress': 'قيد التنفيذ', 'In Progress': 'قيد التنفيذ', 'Completed': 'مكتمل', 'Delivered': 'تم التسليم', 'Cancelled': 'ملغي',
  'TO DO': 'قيد الانتظار', 'IN PROGRESS': 'قيد التنفيذ', 'DONE': 'منجز',

  // vehicles
  'Vehicles': 'المركبات', 'Vehicle': 'المركبة', 'Vehicle #': 'رقم المركبة', 'Brand': 'العلامة التجارية', 'Model': 'الطراز', 'Brand / Model': 'العلامة / الطراز', 'Variant': 'الفئة',
  'Manufacture Year': 'سنة الصنع', 'Color': 'اللون', 'Current KM': 'الكيلومتر الحالي', 'KM': 'كم', 'Km': 'كم', 'Km Driven': 'المسافة المقطوعة (كم)', 'Istimara No.': 'رقم الاستمارة',
  'Chassis #': 'رقم الهيكل', 'Chassis Number': 'رقم هيكل السيارة', 'Engine Number': 'رقم المحرك', 'Vehicle Number (Plate)': 'رقم المركبة (اللوحة)', 'Vehicle Number': 'رقم المركبة',
  'Plate number': 'رقم اللوحة', 'VIN / Chassis': 'رقم الهيكل / VIN', 'e.g. GXL, Limited, LX': 'مثال: GXL، Limited، LX', 'Optional notes': 'ملاحظات اختيارية',
  'Vehicle Identification': 'بيانات المركبة', 'Registration & Technical': 'التسجيل والبيانات الفنية', 'Create New Vehicle': 'إنشاء مركبة جديدة', 'Update Vehicle': 'تحديث المركبة',
  'Vehicle created successfully!': 'تم إنشاء المركبة بنجاح!', 'Vehicle updated successfully!': 'تم تحديث المركبة بنجاح!', 'Failed to process vehicle!': 'فشلت معالجة المركبة!',
  'Customer is required': 'العميل مطلوب', 'Vehicle number is required': 'رقم المركبة مطلوب', 'No Vehicles to display': 'لا توجد مركبات للعرض',
  'Updated automatically from the latest sales or quotation': 'يتم تحديثه تلقائياً من آخر فاتورة أو عرض سعر', 'Select Brand': 'اختر العلامة', 'Select Model': 'اختر الطراز',
  'Select a customer to see details': 'اختر عميلاً لعرض التفاصيل', 'Search customer...': 'ابحث عن عميل...', 'Vehicle History': 'سجل المركبة', 'Repair Job Board': 'لوح مهام الإصلاح',
  'Sales History': 'سجل المبيعات', 'Quotation History': 'سجل عروض الأسعار', 'No repair jobs found': 'لا توجد مهام إصلاح', 'No sales found': 'لا توجد مبيعات', 'No quotations found': 'لا توجد عروض أسعار',
  'Customer vehicles serviced by the workshop': 'مركبات العملاء التي تخدمها الورشة', 'Search plate, chassis, brand, model, istimara or customer…': 'ابحث باللوحة أو الهيكل أو العلامة أو الطراز أو الاستمارة أو العميل…',
  'New vehicle': 'مركبة جديدة', 'Name (Arabic)': 'الاسم (بالعربية)', 'Job #': 'رقم المهمة', 'Type': 'النوع', 'Labour': 'العمالة', 'Payment': 'الدفع', 'Created At': 'تاريخ الإنشاء',

  // repair jobs
  'Repair Jobs': 'مهام الإصلاح', 'Repair Job': 'مهمة إصلاح', 'Repair Jobs Board': 'لوح مهام الإصلاح', 'New Repair Job': 'مهمة إصلاح جديدة', 'New Job': 'مهمة جديدة', 'Job': 'المهمة',
  'Job Number': 'رقم المهمة', 'Job Date': 'تاريخ المهمة', 'Job Information': 'معلومات المهمة', 'Est. Delivery': 'التسليم المتوقع', 'Technician': 'الفني', 'Technicians': 'الفنيون',
  'Net Total': 'الصافي', 'Open/Closed': 'مفتوح/مغلق', 'Parts': 'قطع الغيار', 'Labour Charge': 'رسوم العمالة', 'Parts & Labour': 'قطع الغيار والعمالة', 'Complaint': 'الشكوى',
  'Inspection': 'الفحص', 'Work Done': 'العمل المنجز', 'Service Details': 'تفاصيل الخدمة', 'Customer & Vehicle': 'العميل والمركبة', 'Vehicle & Technician': 'المركبة والفني',
  'Cost Summary': 'ملخص التكلفة', 'Parts (excl. VAT)': 'قطع الغيار (بدون ضريبة)', 'Labour (excl. VAT)': 'العمالة (بدون ضريبة)', 'Subtotal (excl. VAT)': 'المجموع الفرعي (بدون ضريبة)',
  'Total (incl. VAT)': 'الإجمالي (شامل الضريبة)', 'incl. VAT': 'شامل الضريبة', 'Part / Service Name': 'اسم القطعة / الخدمة', 'Part Name': 'اسم القطعة', 'Parts Used': 'القطع المستخدمة',
  'Qty': 'الكمية', 'Stock': 'المخزون', 'Price (excl.)': 'السعر (بدون)', 'Price (incl.)': 'السعر (شامل)', 'L. Disc. (incl. VAT)': 'خصم السطر (شامل الضريبة)',
  'Create New Repair Job': 'إنشاء مهمة إصلاح جديدة', 'Update Repair Job': 'تحديث مهمة الإصلاح', 'Repair job created successfully!': 'تم إنشاء مهمة الإصلاح بنجاح!',
  'Repair job updated successfully!': 'تم تحديث مهمة الإصلاح بنجاح!', 'Failed to process repair job!': 'فشلت معالجة مهمة الإصلاح!', 'Title is required': 'العنوان مطلوب',
  'e.g. Engine overhaul, AC repair, Full service...': 'مثال: إصلاح المحرك، إصلاح المكيف، صيانة كاملة...', 'e.g. Engine overhaul, AC repair...': 'مثال: إصلاح المحرك، إصلاح المكيف...',
  'Describe the customer complaint...': 'صف شكوى العميل...', 'Inspection findings...': 'نتائج الفحص...', 'Work performed...': 'العمل المنجز...',
  'Search & add technician...': 'ابحث وأضف فنياً...', 'Search products or services to add...': 'ابحث عن منتجات أو خدمات لإضافتها...', 'Search vehicle number, brand, model...': 'ابحث برقم المركبة أو العلامة أو الطراز...',
  'Select customer & vehicle': 'اختر العميل والمركبة', 'No parts added yet.': 'لم تتم إضافة قطع بعد.', 'Leave empty for a walk-in (UNKNOWN) customer': 'اتركه فارغاً لعميل نقدي (مجهول)',
  'No Repair Jobs to display': 'لا توجد مهام إصلاح للعرض', 'Job cards for the workshop': 'بطاقات العمل للورشة', 'Search job #, plate, brand, model or technician…': 'ابحث برقم المهمة أو اللوحة أو العلامة أو الطراز أو الفني…',
  'No title': 'بدون عنوان', 'Create Sales Invoice': 'إنشاء فاتورة مبيعات', 'Total must be greater than 0': 'يجب أن يكون الإجمالي أكبر من 0', 'add parts or labour before invoicing.': 'أضف قطعاً أو عمالة قبل الفوترة.',
  'Archive this repair job?': 'أرشفة مهمة الإصلاح هذه؟',

  // board
  'Overdue': 'متأخر', 'Due Today': 'مستحق اليوم', 'Due': 'الاستحقاق', 'Show Archived': 'عرض المؤرشف', 'Hide Archived': 'إخفاء المؤرشف', 'Filter by customer...': 'تصفية حسب العميل...',
  'Search vehicle...': 'ابحث عن مركبة...', 'Add a card': 'إضافة بطاقة', 'Add card': 'إضافة بطاقة', 'Add another list': 'إضافة قائمة أخرى', 'Add list': 'إضافة قائمة', 'Enter list name...': 'أدخل اسم القائمة...',
  'Enter a title for this card...': 'أدخل عنواناً لهذه البطاقة...', 'Delete list': 'حذف القائمة', 'Double-click to rename • Drag to reorder': 'انقر مرتين لإعادة التسمية • اسحب لإعادة الترتيب',
  'This list has {{n}} card(s). Cards will be moved to the first list. Continue?': 'تحتوي هذه القائمة على {{n}} بطاقة. سيتم نقل البطاقات إلى القائمة الأولى. متابعة؟',
  'Add to List': 'إضافة إلى القائمة', 'Create Card': 'إنشاء بطاقة', 'Open Card': 'فتح البطاقة', 'Move to': 'نقل إلى', 'List name': 'اسم القائمة', 'Unassigned': 'غير معين', 'Stage progress': 'تقدم المرحلة',
  'more': 'المزيد', 'scroll or click to load': 'مرر أو انقر للتحميل', '{{n}} cards': '{{n}} بطاقة', 'Drag cards between lists · {{n}} active jobs': 'اسحب البطاقات بين القوائم · {{n}} مهمة نشطة',
  'Customer Required': 'العميل مطلوب', 'Please select a customer from the filter bar before creating a sales invoice or quotation.': 'يرجى اختيار عميل من شريط التصفية قبل إنشاء فاتورة مبيعات أو عرض سعر.',
  'Select Job Cards for Sales Invoice': 'اختر بطاقات العمل لفاتورة المبيعات', 'Select one or more job cards to include.': 'اختر بطاقة عمل واحدة أو أكثر لتضمينها.', 'Net Amount': 'صافي المبلغ',
  'No jobs visible on this board.': 'لا توجد مهام ظاهرة في هذا اللوح.', 'All job cards on this board already have a sales invoice.': 'جميع بطاقات العمل في هذا اللوح لديها فاتورة مبيعات بالفعل.',
  'job': 'مهمة', 'jobs': 'مهام', 'full form': 'النموذج الكامل',

  // employees & salaries
  'Employees': 'الموظفون', 'Employee': 'الموظف', 'New employee': 'موظف جديد', 'Staff, salaries and balances': 'الموظفون والرواتب والأرصدة', 'Search by name, mobile or iqama…': 'ابحث بالاسم أو الجوال أو الإقامة…',
  'Mobile': 'الجوال', 'Mobile 1': 'الجوال 1', 'Mobile 2': 'الجوال 2', 'Iqama No.': 'رقم الإقامة', 'Joining Date': 'تاريخ الالتحاق', 'Address': 'العنوان', 'Active': 'نشط', 'Inactive': 'غير نشط',
  'Full name': 'الاسم الكامل', 'Position / Designation': 'المنصب / المسمى الوظيفي', 'Select position...': 'اختر المنصب...', 'Manage Positions': 'إدارة المناصب', 'New position name...': 'اسم منصب جديد...',
  'No positions defined. Add one above.': 'لا توجد مناصب. أضف واحداً أعلاه.', 'Click to select': 'انقر للاختيار', 'Employee Details': 'بيانات الموظف', 'Employee Info': 'معلومات الموظف', 'Employee Information': 'معلومات الموظف',
  'Salary': 'الراتب', 'Salary Day': 'يوم صرف الراتب', 'Salary Information': 'معلومات الراتب', 'Salary Date (Day of Month)': 'تاريخ الراتب (يوم من الشهر)', 'Day of month (1-28) when salary is due': 'يوم الشهر (1-28) الذي يستحق فيه الراتب',
  'Opening Balance': 'الرصيد الافتتاحي', 'Opening Balance Amount': 'مبلغ الرصيد الافتتاحي', 'Opening Balance As Of': 'الرصيد الافتتاحي بتاريخ', 'Opening Balance (From Previous System)': 'الرصيد الافتتاحي (من النظام السابق)',
  'As Of Date': 'بتاريخ', 'Balance Direction': 'اتجاه الرصيد', 'Store owes Employee': 'المتجر مدين للموظف', 'Employee owes Store': 'الموظف مدين للمتجر', 'This system starts tracking salary due from this date': 'يبدأ النظام تتبع الرواتب المستحقة من هذا التاريخ',
  'If this employee has an outstanding balance from your previous system, enter the amount and date. Leave as 0 if fully settled.': 'إذا كان لهذا الموظف رصيد مستحق من نظامك السابق، أدخل المبلغ والتاريخ. اتركه 0 إذا تمت التسوية بالكامل.',
  '(An opening balance entry has already been posted for this employee — changing the values below will update it.)': '(تم ترحيل قيد رصيد افتتاحي لهذا الموظف — تغيير القيم أدناه سيحدثه.)',
  'Account Balance': 'رصيد الحساب', 'Account Name': 'اسم الحساب', 'Owed to Employee': 'مستحق للموظف', 'Employee Owes': 'ما يدين به الموظف', 'Create New Employee': 'إنشاء موظف جديد', 'Update Employee': 'تحديث الموظف',
  'Employee created successfully!': 'تم إنشاء الموظف بنجاح!', 'Employee updated successfully!': 'تم تحديث الموظف بنجاح!', 'Failed to process employee!': 'فشلت معالجة الموظف!',
  'Name is required': 'الاسم مطلوب', 'Salary is required': 'الراتب مطلوب', 'Salary cannot be negative': 'لا يمكن أن يكون الراتب سالباً', 'Salary day must be between 1 and 28': 'يجب أن يكون يوم الراتب بين 1 و 28',
  'Joining date is required': 'تاريخ الالتحاق مطلوب', 'Opening balance cannot be negative': 'لا يمكن أن يكون الرصيد الافتتاحي سالباً', 'As of date is required when an opening balance is set': 'التاريخ مطلوب عند إدخال رصيد افتتاحي',
  'No Employees to display': 'لا يوجد موظفون للعرض', 'Delete Permanently': 'حذف نهائي', 'Employee deleted permanently': 'تم حذف الموظف نهائياً', 'Unable to delete employee': 'تعذر حذف الموظف',
  'Permanently delete "{{name}}"? This will remove the employee along with ALL related salary payments, accrual entries and balance sheet postings. This cannot be undone.': 'حذف "{{name}}" نهائياً؟ سيؤدي ذلك إلى إزالة الموظف مع جميع مدفوعات الرواتب وقيود الاستحقاق وترحيلات الميزانية المرتبطة. لا يمكن التراجع عن ذلك.',
  'Total Employees': 'إجمالي الموظفين', 'Total Monthly Salary': 'إجمالي الرواتب الشهرية', 'Total Salary Paid': 'إجمالي الرواتب المدفوعة', 'Owed to Employees': 'مستحق للموظفين', 'Employees Owe': 'مستحق على الموظفين', 'Net Balance': 'صافي الرصيد',
  'PAY SALARY': 'صرف الراتب', 'Pay Salary': 'صرف الراتب', 'Pay': 'دفع', 'Salary History': 'سجل الرواتب', 'Salary Payment History': 'سجل مدفوعات الرواتب', 'No salary payments recorded yet.': 'لم يتم تسجيل مدفوعات رواتب بعد.',
  'Total Paid': 'إجمالي المدفوع', 'Payments': 'المدفوعات', 'Period': 'الفترة', 'Edit Salary Payment': 'تعديل دفعة الراتب', 'Update Payment': 'تحديث الدفعة', 'Payment Method': 'طريقة الدفع',
  'Cash (from Cash A/c)': 'نقداً (من حساب النقدية)', 'Bank Transfer (from Bank A/c)': 'تحويل بنكي (من حساب البنك)', 'Cash': 'نقداً', 'Bank': 'البنك', 'Bank Transfer': 'تحويل بنكي',
  'Search by name...': 'ابحث بالاسم...', 'Please select an employee': 'يرجى اختيار موظف', 'Amount must be greater than 0': 'يجب أن يكون المبلغ أكبر من 0',
  'Salary payment recorded successfully!': 'تم تسجيل دفعة الراتب بنجاح!', 'Salary payment updated successfully!': 'تم تحديث دفعة الراتب بنجاح!', 'Failed to record salary payment!': 'فشل تسجيل دفعة الراتب!',
  'Failed to update salary payment!': 'فشل تحديث دفعة الراتب!', 'Salary payment deleted': 'تم حذف دفعة الراتب', 'Failed to delete payment': 'فشل حذف الدفعة', 'Unable to delete': 'تعذر الحذف',
  'Are you sure you want to delete this salary payment? This will reverse the ledger entries.': 'هل أنت متأكد من حذف دفعة الراتب هذه؟ سيؤدي ذلك إلى عكس القيود المحاسبية.',
  'Permanently delete this salary payment of {{amount}} for {{name}}? This cannot be undone.': 'حذف دفعة الراتب بمبلغ {{amount}} لـ {{name}} نهائياً؟ لا يمكن التراجع عن ذلك.',
  'This payment will create a double-entry ledger: Debit employee liability account, Credit': 'ستنشئ هذه الدفعة قيداً مزدوجاً: مدين حساب التزام الموظف، دائن', 'account.': 'الحساب.',
  'Salaries': 'الرواتب', 'Salary payments to employees': 'مدفوعات الرواتب للموظفين', 'Search by employee name…': 'ابحث باسم الموظف…', 'No salary payments to display': 'لا توجد مدفوعات رواتب للعرض',
  'Total Payments': 'إجمالي المدفوعات', 'Total Amount Paid': 'إجمالي المبلغ المدفوع', 'Total Cash': 'إجمالي النقد', 'Total Bank Transfer': 'إجمالي التحويلات البنكية',
  'January': 'يناير', 'February': 'فبراير', 'March': 'مارس', 'April': 'أبريل', 'May': 'مايو', 'June': 'يونيو', 'July': 'يوليو', 'August': 'أغسطس', 'September': 'سبتمبر', 'October': 'أكتوبر', 'November': 'نوفمبر', 'December': 'ديسمبر',
'Senior Technician': 'فني أول', 'Master Technician': 'فني خبير', 'Workshop Manager': 'مدير الورشة', 'Service Advisor': 'مستشار الخدمة', 'Parts Manager': 'مدير قطع الغيار',
  'Receptionist': 'موظف استقبال', 'Cashier': 'أمين الصندوق', 'Electrician': 'كهربائي', 'Mechanic': 'ميكانيكي', 'Painter': 'دهان', 'Welder': 'لحام', 'Body Repair Technician': 'فني سمكرة', 'Quality Inspector': 'مفتش الجودة', 'Driver': 'سائق',

  // dashboard
  'Real-time overview of your automobile workshop operations': 'نظرة عامة فورية على عمليات ورشة السيارات', 'Loading dashboard...': 'جارٍ تحميل لوحة التحكم...',
  'Single Month': 'شهر واحد', 'Month Range': 'نطاق أشهر', 'Single Date': 'تاريخ واحد', 'Date Range': 'نطاق تواريخ', 'Year Range': 'نطاق سنوات', 'Last 12 Months': 'آخر 12 شهراً', 'From': 'من', 'To': 'إلى',
  'Profit Overview': 'نظرة عامة على الأرباح', 'Total Profit': 'إجمالي الربح', 'Monthly Profit': 'الربح الشهري', 'Labour Profit': 'ربح العمالة', 'Spare Profit': 'ربح قطع الغيار', 'Additional Profit': 'ربح إضافي',
  'Cash & Bank': 'النقد والبنك', 'Counter Cash': 'نقد الكاونتر', 'Bank Cash': 'نقد البنك', 'Cash A/c': 'حساب النقدية', 'Bank A/c': 'حساب البنك',
  'Assets & Liabilities': 'الأصول والالتزامات', 'Spare Parts Asset Value': 'قيمة أصول قطع الغيار', 'Purchase': 'الشراء', 'Total Credit': 'إجمالي الائتمان', 'Unpaid Purchase Bill': 'فواتير شراء غير مدفوعة',
  'Salary Balance': 'رصيد الراتب', 'Employees Owe Us': 'مستحق على الموظفين لنا', 'Settled': 'مسوى', 'Additional Expense': 'مصروفات إضافية', 'By Category': 'حسب الفئة', 'By Customer': 'حسب العميل',
  'By Vendor': 'حسب المورد', 'By Employee': 'حسب الموظف', '(−) Store owes employee  ·  (+) Employee owes store': '(−) المتجر مدين للموظف  ·  (+) الموظف مدين للمتجر',
  'TOTAL VAT': 'إجمالي الضريبة', 'Monthly VAT': 'الضريبة الشهرية', 'Payable to Authority': 'مستحقة للهيئة', 'Refundable': 'قابلة للاسترداد', 'Sales VAT': 'ضريبة المبيعات', 'Sales Return VAT': 'ضريبة مرتجعات المبيعات',
  'Purchase VAT': 'ضريبة المشتريات', 'Purchase Return VAT': 'ضريبة مرتجعات المشتريات', 'Expense VAT (w/ Vendor Inv.)': 'ضريبة المصروفات (مع فاتورة مورد)',
  'Charts & Analytics': 'الرسوم البيانية والتحليلات', 'Monthly P&L Trend': 'اتجاه الأرباح والخسائر الشهري', 'Profit Breakdown': 'تفصيل الأرباح', 'Cash Distribution': 'توزيع النقد', 'Assets & Liabilities Overview': 'نظرة عامة على الأصول والالتزامات',
  'Revenue': 'الإيرادات', 'Expense': 'المصروف', 'Profit/Loss': 'الربح/الخسارة', 'Spare Parts (Purchase)': 'قطع الغيار (شراء)', 'Spare Parts (Retail)': 'قطع الغيار (تجزئة)',
  'No monthly data available': 'لا توجد بيانات شهرية', 'No profit data available': 'لا توجد بيانات أرباح', 'No cash data available': 'لا توجد بيانات نقدية',
  '— Revenue —': '— الإيرادات —', '— Expenses —': '— المصروفات —', 'Sales': 'المبيعات', 'Sales Returns': 'مرتجعات المبيعات', 'Quotation Sales': 'مبيعات عروض الأسعار', 'Quotation Returns': 'مرتجعات عروض الأسعار',
  'Non-VAT Sales': 'مبيعات بدون ضريبة', 'Non-VAT Returns': 'مرتجعات بدون ضريبة', 'Non-VAT Net Revenue': 'صافي الإيرادات بدون ضريبة', 'Total Revenue': 'إجمالي الإيرادات', 'Expenses': 'المصروفات',
  'Purchases': 'المشتريات', 'Salary Paid': 'الرواتب المدفوعة', 'Total Expenses': 'إجمالي المصروفات', 'Net Profit': 'صافي الربح', 'Total Profit (with VAT)': 'إجمالي الربح (شامل الضريبة)',
  'Total Profit (without VAT)': 'إجمالي الربح (بدون ضريبة)', 'w/o VAT': 'بدون ضريبة', 'Non-VAT Sales Profit': 'ربح المبيعات بدون ضريبة', 'Non-VAT Return Profit': 'ربح المرتجعات بدون ضريبة',
  'Sales Profit (Labour Charge)': 'ربح المبيعات (رسوم العمالة)', 'Return Profit (Labour Charge)': 'ربح المرتجعات (رسوم العمالة)', 'Sales Profit (Spare Parts)': 'ربح المبيعات (قطع الغيار)',
  'Return Profit (Spare Parts)': 'ربح المرتجعات (قطع الغيار)', 'Sales Profit (Other Services)': 'ربح المبيعات (خدمات أخرى)', 'Return Profit (Other Services)': 'ربح المرتجعات (خدمات أخرى)',
};
