// Arabic strings for customers, receivables, payables and customer packages (keyed by the English text).
export const ar: Record<string, string> = {
  // Customers list
  'Customers': 'العملاء', 'Customer': 'العميل', 'New customer': 'عميل جديد', 'All customers': 'كل العملاء', 'With balance': 'لديهم رصيد', 'Unpaid invoices': 'فواتير غير مدفوعة',
  'Qtn. invoice balance': 'رصيد فواتير العروض', 'Deleted': 'محذوف', 'Created': 'تاريخ الإنشاء', 'Credit balance': 'الرصيد الدائن', 'Credit limit': 'حد الائتمان', 'Sales': 'المبيعات',
  'Churn risk': 'خطر فقدان العميل', 'CLV segment': 'شريحة القيمة الدائمة', 'Paid': 'مدفوع', 'Unpaid sales': 'مبيعات غير مدفوعة', 'Profit': 'الربح', 'Returns': 'المرتجعات', 'Qtn. sales': 'مبيعات العروض',
  'People and companies you sell to — balances, credit and history': 'الأفراد والشركات الذين تبيع لهم — الأرصدة والائتمان والسجل',
  'Search name, phone, VAT no. or code…': 'ابحث بالاسم أو الهاتف أو الرقم الضريبي أو الرمز…', 'ID': 'المعرف', 'Individual': 'فرد', 'Phone': 'الهاتف', 'VAT no.': 'الرقم الضريبي',
  'Invoices': 'الفواتير', 'Last purchase': 'آخر شراء', 'Created at': 'تاريخ الإنشاء', 'Edit': 'تعديل', 'Delete': 'حذف', 'Restore': 'استعادة', 'Name': 'الاسم', 'Name (Arabic)': 'الاسم (عربي)', 'Email': 'البريد الإلكتروني',
  'Critical': 'حرج', 'High': 'مرتفع', 'Medium': 'متوسط', 'Low': 'منخفض', 'High Value': 'قيمة عالية', 'Mid Value': 'قيمة متوسطة', 'Low Value': 'قيمة منخفضة',
  'Delete customer?': 'حذف العميل؟', 'Restore customer?': 'استعادة العميل؟', 'Customer deleted': 'تم حذف العميل', 'Customer restored': 'تمت استعادة العميل',
  'The customer is hidden from lists and pickers. You can restore it later from the “Deleted” view.': 'سيُخفى العميل من القوائم والاختيارات. يمكنك استعادته لاحقاً من عرض «المحذوفة».',
  // Customer form
  'Identity': 'الهوية', 'Contact': 'التواصل', 'National address': 'العنوان الوطني', 'Credit & opening balance': 'الائتمان والرصيد الافتتاحي', 'Remarks': 'ملاحظات', 'Customer photos': 'صور العميل',
  'Auto': 'تلقائي', 'C.R. no.': 'رقم السجل التجاري', 'Country': 'الدولة', 'Not set': 'غير محدد', 'Contact person': 'الشخص المسؤول', 'Phone 2': 'الهاتف 2',
  'Building no.': 'رقم المبنى', 'Street': 'الشارع', 'Street (Arabic)': 'الشارع (عربي)', 'Unit no.': 'رقم الوحدة', 'District': 'الحي', 'District (Arabic)': 'الحي (عربي)', 'City': 'المدينة', 'City (Arabic)': 'المدينة (عربي)',
  'Postal code': 'الرمز البريدي', 'Additional no.': 'الرقم الإضافي', 'Short address': 'العنوان المختصر', '0 = no limit': '0 = بدون حد', 'Opening balance direction': 'اتجاه الرصيد الافتتاحي',
  'Customer owes store': 'العميل مدين للمتجر', 'Store owes customer': 'المتجر مدين للعميل', 'Opening balance': 'الرصيد الافتتاحي', 'As of': 'بتاريخ', 'Use remarks in sales': 'استخدام الملاحظات في المبيعات',
  'Filled automatically from the English name — you can edit it.': 'يُملأ تلقائياً من الاسم الإنجليزي — يمكنك تعديله.',
  'Required for ZATCA tax invoices: 4-digit building no. and 5-digit postal code.': 'مطلوب للفواتير الضريبية لزاتكا: رقم مبنى من 4 أرقام ورمز بريدي من 5 أرقام.',
  'Printed on tax invoices.': 'يُطبع على الفواتير الضريبية.', 'Photos upload right after the customer is created.': 'تُرفع الصور مباشرة بعد إنشاء العميل.',
  'The opening balance is posted to the ledger. Changing the amount, date or direction re-posts it.': 'تم ترحيل الرصيد الافتتاحي إلى الأستاذ. تغيير المبلغ أو التاريخ أو الاتجاه يعيد ترحيله.',
  'Credit & balances': 'الائتمان والأرصدة', 'Qtn. credit invoices': 'فواتير العروض الآجلة', 'Qtn. paid invoices': 'فواتير العروض المدفوعة', 'Tips': 'نصائح',
  'Leave ID empty to generate the next customer number.': 'اترك المعرف فارغاً لتوليد رقم العميل التالي تلقائياً.', 'Names are saved in capitals.': 'تُحفظ الأسماء بأحرف كبيرة.',
  'VAT customers get tax invoices; others get simplified invoices.': 'العملاء المسجلون ضريبياً يحصلون على فواتير ضريبية، والآخرون على فواتير مبسطة.',
  'Record': 'السجل', 'Created by': 'أنشئ بواسطة', 'Updated by': 'حُدّث بواسطة', 'Updated at': 'تاريخ التحديث', 'Save': 'حفظ', 'Save changes': 'حفظ التغييرات', 'Cancel': 'إلغاء', 'New': 'جديد',
  '{{name}} created': 'تم إنشاء {{name}}', 'Saved': 'تم الحفظ', 'Please fix the highlighted fields.': 'يرجى تصحيح الحقول المحددة.', 'Couldn’t save.': 'تعذّر الحفظ.',
  '{{n}} photo(s) could not be uploaded.': 'تعذّر رفع {{n}} صورة.',
  // validation messages (client + server)
  'Name is required': 'الاسم مطلوب', 'Enter a valid email address.': 'أدخل بريداً إلكترونياً صحيحاً.', 'VAT No. should be 15 digits': 'يجب أن يتكون الرقم الضريبي من 15 رقماً',
  'VAT No. should start and end with 3': 'يجب أن يبدأ الرقم الضريبي وينتهي بالرقم 3', 'Registration Number should be alpha numeric(a-zA-Z|0-9)': 'يجب أن يحتوي رقم السجل على حروف وأرقام فقط',
  'Building number should be 4 digits': 'يجب أن يتكون رقم المبنى من 4 أرقام', 'Zip code should be 5 digits': 'يجب أن يتكون الرمز البريدي من 5 أرقام', 'Enter a valid amount.': 'أدخل مبلغاً صحيحاً.',
  'Opening balance cannot be negative': 'لا يمكن أن يكون الرصيد الافتتاحي سالباً', 'Opening balance date is required when an opening balance is entered': 'تاريخ الرصيد الافتتاحي مطلوب عند إدخال رصيد افتتاحي',
  'ID already exists.': 'المعرف موجود مسبقاً.', 'Customer is required': 'العميل مطلوب', 'Vendor is required': 'المورد مطلوب', 'Employee is required': 'الموظف مطلوب', 'Date is required': 'التاريخ مطلوب',
  'Payment date is required': 'تاريخ الدفعة مطلوب', 'Payment amount is required': 'مبلغ الدفعة مطلوب', 'Payment amount should be greater than zero': 'يجب أن يكون مبلغ الدفعة أكبر من صفر',
  'Payment discount should not be grater than amount': 'يجب ألا يتجاوز الخصم مبلغ الدفعة', 'Payment method is required': 'طريقة الدفع مطلوبة', 'At least one payment is required': 'مطلوب دفعة واحدة على الأقل',
  'Payment date time should be greater than or equal to Receivable date time': 'يجب أن يكون تاريخ الدفعة بعد أو يساوي تاريخ سند القبض',
  'Payment date time should be greater than or equal to Payable date time': 'يجب أن يكون تاريخ الدفعة بعد أو يساوي تاريخ سند الصرف',
  'Payment is already closed for this invoice': 'تم سداد هذه الفاتورة بالكامل', 'Invoice is not belongs to the selected customer': 'الفاتورة لا تخص العميل المحدد',
  // Photos
  'Add photos': 'إضافة صور', 'Remove photo': 'إزالة الصورة', 'View photo': 'عرض الصورة', 'Photo': 'صورة', 'No photos yet.': 'لا توجد صور بعد.', 'Uploads when you save': 'تُرفع عند الحفظ',
  'Only images up to 10 MB can be added.': 'يمكن إضافة الصور حتى 10 ميجابايت فقط.', 'Photo uploaded': 'تم رفع الصورة', 'Photo removed': 'تمت إزالة الصورة', 'Remove this photo?': 'إزالة هذه الصورة؟', 'Remove': 'إزالة',
  // Customer 360
  'Active': 'نشط', 'Over credit limit': 'تجاوز حد الائتمان', 'Lifetime sales': 'إجمالي المبيعات', 'Open balance': 'الرصيد المفتوح', 'Customer since': 'عميل منذ', 'Overview': 'نظرة عامة',
  'Quotations': 'عروض الأسعار', 'Payments': 'المدفوعات', 'Ledger': 'الأستاذ', 'Vehicles': 'المركبات', 'Contacts & addresses': 'جهات الاتصال والعناوين', 'Churn & CLV': 'الفقد والقيمة الدائمة',
  'New invoice': 'فاتورة جديدة', 'Receive payment': 'استلام دفعة', 'Statement': 'كشف حساب', 'Sections': 'الأقسام', 'This customer is deleted.': 'هذا العميل محذوف.',
  'It is hidden from lists and pickers. Restore it to sell to this customer again.': 'إنه مخفي من القوائم والاختيارات. استعده لتتمكن من البيع لهذا العميل مجدداً.',
  'Receivables aging': 'أعمار الذمم المدينة', 'Open invoice balance by days since invoice': 'رصيد الفواتير المفتوحة حسب عمر الفاتورة بالأيام', 'No open invoices — nothing overdue.': 'لا توجد فواتير مفتوحة — لا شيء متأخر.',
  'Credit': 'الائتمان', 'Credit used {{p}}': 'الائتمان المستخدم {{p}}', 'No credit limit': 'بدون حد ائتمان', 'Limit': 'الحد', 'Used': 'المستخدم', 'Available': 'المتاح', 'All details': 'كل التفاصيل',
  'No contact person': 'لا يوجد شخص مسؤول', 'Open invoices': 'الفواتير المفتوحة', 'All invoices are paid.': 'جميع الفواتير مدفوعة.', 'Invoice #': 'رقم الفاتورة', 'Date': 'التاريخ', 'Age': 'العمر',
  'Total': 'الإجمالي', 'Balance': 'الرصيد', 'Status': 'الحالة', '{{n}} days': '{{n}} يوم', 'Overdue': 'متأخرة', 'View all {{n}} open invoices': 'عرض كل الفواتير المفتوحة ({{n}})',
  'Sales summary': 'ملخص المبيعات', 'This store, all time': 'هذا الفرع، كل الأوقات', 'Unpaid': 'غير مدفوع', 'Qtn. invoices': 'فواتير العروض', 'Delivery notes': 'إشعارات التسليم',
  'Sales invoices': 'فواتير المبيعات', 'No invoices yet': 'لا توجد فواتير بعد', 'Filter': 'تصفية', 'All': 'الكل', 'Open': 'مفتوح', 'Payment': 'الدفع',
  'Sales returns': 'مرتجعات المبيعات', 'No returns': 'لا توجد مرتجعات', 'Return #': 'رقم المرتجع', 'Refund': 'الاسترداد',
  'No quotations yet': 'لا توجد عروض أسعار بعد', 'New quotation': 'عرض سعر جديد', 'Quotation #': 'رقم العرض', 'Type': 'النوع', 'Invoice': 'فاتورة', 'Quotation': 'عرض سعر', 'Converted': 'تم التحويل',
  'Receipts from customer': 'مقبوضات من العميل', 'Payments to customer': 'مدفوعات للعميل', 'No payments recorded.': 'لا توجد مدفوعات مسجلة.', 'Cash': 'نقدي', 'Bank': 'بنك',
  'Direction': 'الاتجاه', 'Received': 'مقبوض', 'Paid out': 'مدفوع', 'Pay customer': 'الدفع للعميل', 'Payment methods': 'طرق الدفع', 'Description': 'الوصف', 'Net total': 'الصافي',
  'No vehicles registered': 'لا توجد مركبات مسجلة', 'Add vehicle': 'إضافة مركبة', 'Plate no.': 'رقم اللوحة', 'Vehicle': 'المركبة', 'Chassis no.': 'رقم الهيكل', 'Odometer': 'العداد', 'Color': 'اللون',
  'Posted to ledger': 'مرحّل إلى الأستاذ', 'Yes': 'نعم', 'No': 'لا', 'used in sales': 'تُستخدم في المبيعات',
  'Churn & CLV history': 'سجل الفقد والقيمة الدائمة', 'Latest 100 snapshots, newest first': 'آخر 100 لقطة، الأحدث أولاً', 'History': 'السجل', 'CLV': 'القيمة الدائمة', 'No history yet.': 'لا يوجد سجل بعد.',
  'Risk tier': 'مستوى الخطر', 'Churn %': 'نسبة الفقد', 'Total spend': 'إجمالي الإنفاق', 'Days since last buy': 'أيام منذ آخر شراء', 'Reason': 'السبب', 'Predicted CLV (12m)': 'القيمة المتوقعة (12 شهراً)',
  'Avg. order': 'متوسط الطلب', 'Orders': 'الطلبات', 'Spend': 'الإنفاق', 'Records': 'السجلات', 'Totals': 'الإجماليات',
  // Statement
  'Account statement': 'كشف الحساب', 'A/c #{{n}}': 'حساب رقم {{n}}', 'newest first': 'الأحدث أولاً', 'Export': 'تصدير', 'From': 'من', 'To': 'إلى', 'Clear filters': 'مسح الفلاتر',
  'Debit total': 'إجمالي المدين', 'Credit total': 'إجمالي الدائن', 'Closing balance': 'الرصيد الختامي', 'Particulars': 'البيان', 'Debit': 'مدين',
  'No ledger entries yet.': 'لا توجد قيود بعد.', 'The ledger account is created with the first invoice, receipt or opening balance.': 'يُنشأ حساب الأستاذ مع أول فاتورة أو سند قبض أو رصيد افتتاحي.',
  'No entries in this period.': 'لا توجد قيود في هذه الفترة.', 'Exported {{n}} rows': 'تم تصدير {{n}} صف', 'Customer Deposit': 'سند قبض', 'Customer Withdrawal': 'سند صرف', 'Sales Return': 'مرتجع مبيعات',
  'Quotation Sales': 'مبيعات العروض', 'Customer Opening Balance': 'رصيد افتتاحي للعميل',
  // Receivables / payables
  'Receivables': 'الذمم المدينة', 'Payables': 'الذمم الدائنة', 'Receivable': 'سند قبض', 'Payable': 'سند صرف', 'New receivable': 'سند قبض جديد', 'New payable': 'سند صرف جديد',
  'Money received from customers, vendors and employees': 'المبالغ المستلمة من العملاء والموردين والموظفين',
  'Money paid out to customers, vendors and employees (refunds, advances)': 'المبالغ المدفوعة للعملاء والموردين والموظفين (استردادات وسلف)',
  'Search ID or description…': 'ابحث بالمعرف أو الوصف…', 'Vendors': 'الموردون', 'Employees': 'الموظفون', 'Not reported to ZATCA': 'لم يُبلّغ لزاتكا',
  'Vendor': 'المورد', 'Employee': 'الموظف', 'Payment method': 'طريقة الدفع', 'Amount': 'المبلغ', 'e.g. >=1000': 'مثال: >=1000', 'Purchase fund': 'صندوق المشتريات', 'Purchase fund A/c': 'حساب صندوق المشتريات',
  'From customers': 'من العملاء', 'From vendors': 'من الموردين', 'To customers': 'إلى العملاء', 'To vendors': 'إلى الموردين', 'Received from': 'مستلم من', 'Paid to': 'مدفوع إلى',
  'ZATCA': 'زاتكا', 'Print receipt': 'طباعة السند', 'Print': 'طباعة', 'Receipt': 'سند',
  'Debit card': 'بطاقة مدى', 'Credit card': 'بطاقة ائتمان', 'Bank card': 'بطاقة بنكية', 'Bank transfer': 'تحويل بنكي', 'Bank cheque': 'شيك بنكي',
  'Details': 'التفاصيل', 'Current balance': 'الرصيد الحالي', 'Search by name, phone, VAT no., code…': 'ابحث بالاسم أو الهاتف أو الرقم الضريبي أو الرمز…', 'Bank reference': 'المرجع البنكي',
  'Add payment': 'إضافة دفعة', 'Method': 'الطريقة', 'Select': 'اختر', 'Discount': 'الخصم', 'Note': 'ملاحظة', 'Link invoice': 'ربط فاتورة', 'Remove invoice link': 'إزالة ربط الفاتورة',
  'Select the party first': 'اختر الطرف أولاً', 'Remove payment': 'حذف الدفعة', 'Attachments': 'المرفقات', 'Add attachment': 'إضافة مرفق', 'Remove attachment': 'إزالة المرفق', 'No attachments': 'لا توجد مرفقات',
  'Summary': 'الملخص', 'Report to ZATCA as debit note on create': 'إبلاغ زاتكا كإشعار مدين عند الإنشاء', 'Report to ZATCA as credit note on create': 'إبلاغ زاتكا كإشعار دائن عند الإنشاء',
  'This record was reported to ZATCA and can’t be edited.': 'تم إبلاغ زاتكا بهذا السجل ولا يمكن تعديله.', 'Remove the linked invoices before changing the type.': 'أزل الفواتير المرتبطة قبل تغيير النوع.',
  'Invoice links were removed because the party changed.': 'أُزيلت روابط الفواتير لأن الطرف تغيّر.', 'Remove this invoice from the payment?': 'إزالة هذه الفاتورة من الدفعة؟',
  'Link an invoice': 'ربط فاتورة', 'Invoice type': 'نوع الفاتورة', 'Search invoice #': 'ابحث برقم الفاتورة',
  'Only unpaid and partially paid documents of this party are listed. The amount is set to the open balance.': 'تظهر فقط المستندات غير المدفوعة أو المدفوعة جزئياً لهذا الطرف. يُضبط المبلغ على الرصيد المفتوح.',
  'Sales invoice': 'فاتورة مبيعات', 'Quotation invoice': 'فاتورة عرض سعر', 'Purchase return': 'مرتجع مشتريات', 'Sales return': 'مرتجع مبيعات', 'Quotation sales return': 'مرتجع مبيعات العروض', 'Purchase bill': 'فاتورة مشتريات',
  '{{code}} created': 'تم إنشاء {{code}}', 'Report to ZATCA': 'إبلاغ زاتكا', 'Reported to ZATCA': 'تم الإبلاغ لزاتكا', 'ZATCA rejected this record.': 'رفضت زاتكا هذا السجل.',
  'Reported to ZATCA — this record is read-only.': 'تم الإبلاغ لزاتكا — هذا السجل للقراءة فقط.', 'Notes': 'ملاحظات', 'Close': 'إغلاق',
  // Customer packages
  'Customer packages': 'باقات العملاء', 'Menu packages for SaaS stores — which sidebar tabs a store gets': 'باقات القوائم لمتاجر الاشتراك — أي تبويبات القائمة يحصل عليها المتجر',
  'Search package name…': 'ابحث باسم الباقة…', 'New package': 'باقة جديدة', 'New customer package': 'باقة عميل جديدة', 'Edit package': 'تعديل الباقة', 'Code': 'الرمز', 'Tabs enabled': 'التبويبات المفعّلة',
  '{{n}} tabs': '{{n}} تبويب', 'Enabled menu tabs': 'تبويبات القائمة المفعّلة', 'Select all': 'تحديد الكل', 'Clear all': 'مسح الكل', 'admin': 'مسؤول', 'Create': 'إنشاء',
  'Delete package?': 'حذف الباقة؟', 'Package deleted': 'تم حذف الباقة', 'Stores using this package keep their current tabs until it is changed.': 'تحتفظ المتاجر التي تستخدم هذه الباقة بتبويباتها الحالية حتى يتم تغييرها.',
  'Name is already in use': 'الاسم مستخدم مسبقاً',
};
