/** Arabic for every string in this module (keys are the English source text). */
export const ar: Record<string, string> = {
  "Add at least one item.": "أضف صنفاً واحداً على الأقل.",
  "All cash discounts on an invoice must stay below the amount received on it.": "يجب أن يبقى مجموع الخصومات النقدية على الفاتورة أقل من المبلغ المستلم عليها.",
  "All returns": "كل المرتجعات",
  "All sales": "كل المبيعات",
  "Amount": "المبلغ",
  "Amount can’t exceed the balance due ({{b}}).": "لا يمكن أن يتجاوز المبلغ الرصيد المستحق ({{b}}).",
  "Balance": "الرصيد",
  "Balance due": "المبلغ المستحق",
  "Bank card": "بطاقة بنكية",
  "Bank cheque": "شيك بنكي",
  "Bank reference": "المرجع البنكي",
  "Bank refunds": "مرتجعات بنكية",
  "Bank transfer": "تحويل بنكي",
  "Cancel": "إلغاء",
  "Cash": "نقداً",
  "Cash discount": "الخصم النقدي",
  "Cash discount is deducted from the total and again from the balance (server rule).": "يُخصم الخصم النقدي من الإجمالي ثم مرة أخرى من الرصيد (قاعدة الخادم).",
  "Cash discount must be less than the total.": "يجب أن يكون الخصم النقدي أقل من الإجمالي.",
  "Cash discount must be less than {{b}} (amount received).": "يجب أن يكون الخصم النقدي أقل من {{b}} (المبلغ المستلم).",
  "Cash discount returned": "الخصم النقدي المرتجع",
  "Cash discounts": "الخصومات النقدية",
  "Cash refunds": "مرتجعات نقدية",
  "Clear": "مسح",
  "Close": "إغلاق",
  "Compliance failed": "فشل الامتثال",
  "Couldn’t save.": "تعذر الحفظ.",
  "Create return": "إنشاء مرتجع",
  "Created at": "تاريخ الإنشاء",
  "Created automatically — edit it from its source document.": "أُنشئ تلقائياً — عدّله من المستند المصدر.",
  "Created by": "أنشئ بواسطة",
  "Credit (not refunded)": "رصيد دائن (غير مسترد)",
  "Credit balance": "الرصيد الدائن",
  "Credit card": "بطاقة ائتمان",
  "Credit notes issued against sales invoices": "إشعارات دائنة صادرة مقابل فواتير المبيعات",
  "Customer": "العميل",
  "Customer PO #": "رقم أمر الشراء",
  "Customer account": "حساب العميل",
  "Date": "التاريخ",
  "Date is required": "التاريخ مطلوب",
  "Debit card": "بطاقة مدى",
  "Delete": "حذف",
  "Delete return {{code}}?": "حذف المرتجع {{code}}؟",
  "Delete sale {{code}}?": "حذف البيع {{code}}؟",
  "Delete this {{what}}?": "حذف {{what}}؟",
  "Deleted": "محذوف",
  "Details": "التفاصيل",
  "Disc.": "خصم",
  "Discard": "تجاهل",
  "Discount": "الخصم",
  "Discount can’t exceed the unit price.": "لا يمكن أن يتجاوز الخصم سعر الوحدة.",
  "Discount returned": "الخصم المرتجع",
  "Discounts given at payment time on sales invoices": "خصومات ممنوحة عند السداد على فواتير المبيعات",
  "Download PDF": "تنزيل PDF",
  "Draft": "مسودة",
  "Edit": "تعديل",
  "Edit {{what}}": "تعديل {{what}}",
  "Enter an amount greater than zero.": "أدخل مبلغاً أكبر من صفر.",
  "Exclude product tax": "استثناء ضريبة المنتجات",
  "Exclude service tax": "استثناء ضريبة الخدمات",
  "Fully returned": "مرتجع بالكامل",
  "Hash": "التجزئة",
  "Invoice": "فاتورة",
  "Invoice #": "رقم الفاتورة",
  "Invoice total": "إجمالي الفاتورة",
  "Item": "الصنف",
  "Items": "الأصناف",
  "Items to return": "الأصناف المرتجعة",
  "Locked by ZATCA": "مقفل بواسطة زاتكا",
  "Method": "الطريقة",
  "Methods": "طرق الدفع",
  "Money paid back to customers for sales returns": "المبالغ المعادة للعملاء عن مرتجعات المبيعات",
  "Money received against sales invoices": "المبالغ المستلمة مقابل فواتير المبيعات",
  "Name must be at least 3 characters.": "يجب ألا يقل الاسم عن 3 أحرف.",
  "Name must be at least {{n}} characters.": "يجب ألا يقل الاسم عن {{n}} أحرف.",
  "Net loss": "صافي الخسارة",
  "Net loss returned": "صافي الخسارة المرتجعة",
  "Net profit": "صافي الربح",
  "Net profit returned": "صافي الربح المرتجع",
  "Net total": "الصافي",
  "New cash discount": "خصم نقدي جديد",
  "New non-VAT sale": "بيع جديد بدون ضريبة",
  "New non-VAT sales return": "مرتجع مبيعات بدون ضريبة جديد",
  "New return": "مرتجع جديد",
  "New sales return": "مرتجع مبيعات جديد",
  "New {{what}}": "{{what}} جديد",
  "No": "لا",
  "No VAT invoice": "فاتورة بدون ضريبة",
  "Non-VAT sale": "بيع بدون ضريبة",
  "Non-VAT sales": "مبيعات بدون ضريبة",
  "Non-VAT sales returns": "مرتجعات المبيعات بدون ضريبة",
  "Not refunded": "غير مسترد",
  "Not reported": "لم يتم الإبلاغ",
  "Note": "ملاحظة",
  "Only {{n}} can be returned.": "يمكن إرجاع {{n}} فقط.",
  "Open balance": "رصيد مفتوح",
  "Paid": "مدفوعة",
  "Payment": "الدفع",
  "Payment method": "طريقة الدفع",
  "Payment method is required": "طريقة الدفع مطلوبة",
  "Payment status": "حالة الدفع",
  "Phone": "الهاتف",
  "Please fix the highlighted fields.": "يرجى تصحيح الحقول المحددة.",
  "Print": "طباعة",
  "Quantity can’t be negative.": "لا يمكن أن تكون الكمية سالبة.",
  "Quantity can’t be zero.": "لا يمكن أن تكون الكمية صفراً.",
  "Receive payment": "استلام دفعة",
  "Receive sales payment": "استلام دفعة مبيعات",
  "Received on invoice": "المستلم على الفاتورة",
  "Record refund": "تسجيل استرداد",
  "Record return refund": "تسجيل استرداد مرتجع",
  "Records": "السجلات",
  "Reference": "المرجع",
  "Refund": "استرداد",
  "Refund status": "حالة الاسترداد",
  "Refund to customer": "المبلغ المعاد للعميل",
  "Refunded": "المسترد",
  "Refunds": "المبالغ المستردة",
  "Refunds can’t exceed {{n}}.": "لا يمكن أن تتجاوز المبالغ المستردة {{n}}.",
  "Remarks": "ملاحظات",
  "Report to ZATCA": "إبلاغ زاتكا",
  "Report to ZATCA on save": "الإبلاغ لزاتكا عند الحفظ",
  "Reported": "تم الإبلاغ",
  "Reporting failed": "فشل الإبلاغ",
  "Restore": "استعادة",
  "Return": "مرتجع",
  "Return #": "رقم المرتجع",
  "Return date": "تاريخ المرتجع",
  "Return deleted": "تم حذف المرتجع",
  "Return qty": "كمية الإرجاع",
  "Return quantity": "كمية الإرجاع",
  "Return refund": "استرداد مرتجع",
  "Return refunds": "استردادات المرتجعات",
  "Return total": "إجمالي المرتجع",
  "Returned": "مرتجع",
  "Returns": "المرتجعات",
  "Returns against non-VAT sales": "مرتجعات مقابل المبيعات بدون ضريبة",
  "Returns are always issued against a sales invoice. Search by invoice number or customer.": "تصدر المرتجعات دائماً مقابل فاتورة مبيعات. ابحث برقم الفاتورة أو العميل.",
  "Sale": "البيع",
  "Sale #": "رقم البيع",
  "Sale deleted": "تم حذف البيع",
  "Sales": "المبيعات",
  "Sales invoice": "فاتورة المبيعات",
  "Sales payment": "دفعة مبيعات",
  "Sales payments": "مدفوعات المبيعات",
  "Sales return": "مرتجع مبيعات",
  "Sales return #": "رقم مرتجع المبيعات",
  "Sales returns": "مرتجعات المبيعات",
  "Sales without a tax invoice": "مبيعات بدون فاتورة ضريبية",
  "Save": "حفظ",
  "Save & new": "حفظ وجديد",
  "Save changes": "حفظ التغييرات",
  "Saved": "تم الحفظ",
  "Search by name, phone, VAT no., code…": "ابحث بالاسم أو الهاتف أو الرقم الضريبي أو الرمز…",
  "Search by number or customer…": "ابحث بالرقم أو العميل…",
  "Search by sale number or customer.": "ابحث برقم البيع أو العميل.",
  "Search return # or customer…": "ابحث برقم المرتجع أو العميل…",
  "Search return # or invoice #…": "ابحث برقم المرتجع أو الفاتورة…",
  "Search sale # or customer…": "ابحث برقم البيع أو العميل…",
  "Search…": "بحث…",
  "Select all": "تحديد الكل",
  "Select all items": "تحديد كل الأصناف",
  "Select at least one item to return.": "اختر صنفاً واحداً على الأقل للإرجاع.",
  "Settled against sales": "مسوّى مقابل المبيعات",
  "Sold": "المباع",
  "Status": "الحالة",
  "Still to refund": "المتبقي للاسترداد",
  "Stock added by this return is removed again.": "سيتم خصم المخزون الذي أضافه هذا المرتجع.",
  "Stock and the invoice’s returned quantities are reversed. An admin can restore it later.": "يتم عكس المخزون والكميات المرتجعة في الفاتورة. يمكن للمسؤول استعادته لاحقاً.",
  "Summary": "الملخص",
  "System": "النظام",
  "Tax": "الضريبة",
  "The document’s paid amount and balance are recalculated.": "سيُعاد احتساب المبلغ المدفوع والرصيد للمستند.",
  "The return total can’t exceed the invoice total ({{n}}).": "لا يمكن أن يتجاوز إجمالي المرتجع إجمالي الفاتورة ({{n}}).",
  "The sale is removed from lists and stock is restored.": "يُزال البيع من القوائم ويُستعاد المخزون.",
  "This invoice was never paid, so nothing is refunded — the return reduces what the customer owes.": "لم تُدفع هذه الفاتورة، لذا لا يوجد استرداد — يخفض المرتجع ما يدين به العميل.",
  "This return was deleted. Stock and invoice quantities were reversed.": "تم حذف هذا المرتجع وعكس المخزون وكميات الفاتورة.",
  "This return was reported to ZATCA: items, prices, discount and shipping can’t change. Refunds can still be edited.": "تم إبلاغ زاتكا بهذا المرتجع: لا يمكن تغيير الأصناف والأسعار والخصم والشحن. لا يزال بالإمكان تعديل الاستردادات.",
  "Total": "الإجمالي",
  "Total cash discount": "إجمالي الخصم النقدي",
  "Total payment can’t exceed {{n}}.": "لا يمكن أن يتجاوز إجمالي الدفع {{n}}.",
  "Total received": "إجمالي المستلم",
  "Total refunded": "إجمالي المسترد",
  "Unit discount": "خصم الوحدة",
  "Unit price": "سعر الوحدة",
  "Unit price can’t be zero.": "لا يمكن أن يكون سعر الوحدة صفراً.",
  "Unsaved": "غير محفوظ",
  "Up to {{n}} can be refunded": "يمكن استرداد حتى {{n}}",
  "Use “{{q}}” as the customer name": "استخدم “{{q}}” كاسم العميل",
  "VAT": "الضريبة",
  "VAT returned": "الضريبة المرتجعة",
  "WhatsApp": "واتساب",
  "Which invoice is being returned?": "ما الفاتورة التي يتم إرجاعها؟",
  "Which non-VAT sale is being returned?": "ما البيع بدون ضريبة الذي يتم إرجاعه؟",
  "Yes": "نعم",
  "ZATCA attention": "تحتاج انتباه زاتكا",
  "ZATCA rejected this credit note.": "رفضت زاتكا هذا الإشعار الدائن.",
  "e.g. >=1000": "مثال: >=1000",
  "ex VAT": "بدون ضريبة",
  "incl. VAT": "شامل الضريبة",
  "issued as a credit note.": "يصدر كإشعار دائن.",
  "max": "الحد",
  "per unit": "للوحدة",
  "{{code}} created": "تم إنشاء {{code}}",
  "{{f}} is required": "{{f}} مطلوب",
  "{{n}} of {{m}} items selected": "تم تحديد {{n}} من {{m}} صنف",
  "{{what}} of {{a}} recorded": "تم تسجيل {{what}} بمبلغ {{a}}",
};
